### ISSUE TITLE
The results of CPMNet in MICCAI2021(song et al.)

### ISSUE THREAD

**Issue by Luoxd1996** [MIC-DKFZ/nnDetection#1]
Hi, Dr. Michael Baumgartner, 
Great work for medical image detection, thank you for reviewing our work (CPMNet in MICCAI2021) in this repo. To better report the results of our work, we list the detailed result: 0.125（72.3）0.25（83.8）  0.5（88.7） 1（91.1）2（92.8）4（93.4）8（94.8）average 88.1. And more recent work, SANet: A slice-aware network for pulmonary nodule detection (TPAMI2021) also report the results on LUNA16.
Best,
Xiangde.

**Comment by mibaumgartner** [comment]
I added a table with all numerical values and references in 07f22a0 . Thanks again, for the complete set of numbers. Since this list only includes methods that were published before we submitted our Paper in March 2021, I did not add SANet to the list.
