### ISSUE TITLE
[Question]The training time for training the ribfrac dataset is too long

### ISSUE THREAD

**Issue by BelieferQAQ** [MIC-DKFZ/nnDetection#102]
### :question: Question

Hello, I train the ribfrac dataset. One epoch takes 4 hours. How long is the normal time? I use 3090ti and SSD. In addition, there are 20 CTS in the ribfrac data set that do not contain foreground. Is it right not to put these 20 CTS into the data set to avoid increasing the training time?

![1b4df3aa78b1afa820748232ab53af5](https://user-images.githubusercontent.com/91660759/184829003-b2527c24-1ef4-405e-ab58-edd300220e2e.jpg)
![image](https://user-images.githubusercontent.com/91660759/184829056-8cdc53eb-a9ba-436a-ae74-b70d3ed1de21.png)

**Comment by mibaumgartner** [comment]
Dear @BelieferQAQ ,

the entire training on a RTX2080TI usually takes around 2 days. One epoch should take around 1-2 hours (depending on hardware while 2 hours would be at the upper end). Looking at the screenshot it seems like it is a CPU bottleneck, so increasing `det_num_threads` should help: Make sure to have enough RAM when increasing the number of threads though.

Best,
Michael

**Comment by mibaumgartner** [comment]
I added a "slow training section" to the readme which summarises some common problems and debugging steps to the readme FAQ. The information was previously scattered around several Issues, I hope this helps :)

**Comment by BelieferQAQ** [comment]
> 



> Dear @BelieferQAQ ,
> 
> the entire training on a RTX2080TI usually takes around 2 days. One epoch should take around 1-2 hours (depending on hardware while 2 hours would be at the upper end). Looking at the screenshot it seems like it is a CPU bottleneck, so increasing `det_num_threads` should help: Make sure to have enough RAM when increasing the number of threads though.
> 
> Best, Michael
thank you！My det_ num_ Threads has been set to 12. Do you want to continue adding? Moreover, the training time of each round is gradually increasing. For example, the first round is 4 hours, the second round is 4 hours and 20 minutes, and the third round is 4 hours and 30 minutes，why？

**Comment by mibaumgartner** [comment]
The training time shouldn't increase over time, maybe there are some other factors influencing that as well (e.g. other users running jobs on the machine). Please check, the readme section for additional debugging steps and on how to identify the bottleneck. Increasing det_num_threads only helps if it is a CPU bottleneck but it won't change the time if it is an IO bottleneck.

**Comment by BelieferQAQ** [comment]
> The training time shouldn't increase over time, maybe there are some other factors influencing that as well (e.g. other users running jobs on the machine). Please check, the readme section for additional debugging steps and on how to identify the bottleneck. Increasing det_num_threads only helps if it is a CPU bottleneck but it won't change the time if it is an IO bottleneck.

Thank you very much. Hello, excuse me. Due to the limitation of hardware, the training time is long. I need to train until the middle time (I don't train 50 epochs, maybe 30 epochs), and stop the training after finding the best index.
How to integrate the weight obtained by the 50% cross validation after five times of training

**Comment by mibaumgartner** [comment]
The best model is automatically saved in training directory. Please be aware that shortening the training on RibFrac will decrease results. Since it is the largest dataset in the pool, even the current schedule is slightly to short.

**Comment by BelieferQAQ** [comment]
> 



> The best model is automatically saved in training directory. Please be aware that shortening the training on RibFrac will decrease results. Since it is the largest dataset in the pool, even the current schedule is slightly to sh

thank you！It is said that the low resolution training mode is much faster than the high resolution training mode. How can I switch to the low resolution mode?

**Comment by mibaumgartner** [comment]
The low resolution model does not train faster than the full resolution one. Training time scales with the used patch size and (in contrast to the natural image processing) the patch size remains the same between full and low resolution. The low resolution model uses a downsampled version of the patients which would result in faster inference times.

**Comment by mibaumgartner** [comment]
Since there was no update for some time I’ll close this Issue for now.
Please feel free to reopen this Issue if the problem persists or open a new one.

**Comment by manellopez13** [comment]
Hi, I'm running the training on a Docker image created with the Dockerfile. Training is rather slow, just like @BelieferQAQ said (around 4 h per epoch). I'm trying to rerun with higher `det_num_threads`, just modifying the value of this environment variable before executing `nndet_train` on the image, but I'm not sure this is right, as I don't observe any improvement...

I see that `det_num_threads` is defined in the Dockerfile, but I couldn't find any dependency with any package that is installed or the script... Apologies, I'm quite new with this Docker thing...

My question is: do I have to create a new image with, say, `ARG env_det_num_threads=12` in the Dockerfile ? Or I can really use the same image and just modify the environment variable before executing my jobs ?

**Comment by mibaumgartner** [comment]
I think it should be possible to change the number of det_num_threads without rebuilding the container. You can always check the current number of workers by checking the load on your CPU :)
