### ISSUE TITLE
output with bounding box image

### ISSUE THREAD

**Issue by orouskhani** [MIC-DKFZ/nnDetection#105]
Hello All, 

nnDetection provides some results as json file. Could you please let me know where I can find the output as an image with bounding box surrounded.  

Regards,
Maysam

**Comment by mibaumgartner** [comment]
Dear @orouskhani,

you can refer to this https://github.com/MIC-DKFZ/nnDetection/issues/16 issue for more information on visualization. Note: this is only intended for visual inspection and should not be used for quantitative evaluation. 

Best,
Michael

**Comment by orouskhani** [comment]
Dear Michael,'

That's awesome. Thank you!
