### ISSUE TITLE
3D Coordination of Aneurysm 

### ISSUE THREAD

**Issue by orouskhani** [MIC-DKFZ/nnDetection#106]
Hello All,

Thank you for your comments and helps. I have already used nnDetection for ADAM dataset. I run the convert.py to generate the coordination. However, the result.txt provides the coordination as 6 numbers while it should be 3 numbers. Could you please let me know what the problem is?
This is the text printed in result.txt -->
238,264,49
297,269,47238,264,49
297,269,47238,264,49
297,269,47

Regards,
Maysam

**Comment by mibaumgartner** [comment]
Dear @orouskhani ,

there should be 3 number per line (/detection). The triplets look like duplicates, is it possible that you executed the script several times without deleting the previous files?

Best,
Michael

**Comment by orouskhani** [comment]
Dear Michael,

It worked! thank you for your help.

Regards,
Maysam
