### ISSUE TITLE
no scripts in projects/Task025_LymphNodes

### ISSUE THREAD

**Issue by yyrui** [MIC-DKFZ/nnDetection#111]
Sorry to bother, I cannot find the "projects/Task025_LymphNodes/scripts" folder for Task025 data preparing.
Thanks if you can help!

**Comment by mibaumgartner** [comment]
Dear @yyrui ,

indeed, we manually splitted the lymph node dataset into abdomen and mediastinum in a bugfix at some point but didn't update the automatic script yet. I'll upload an updated version during the next week.

Best,
Michael

**Comment by yyrui** [comment]
Got it! Thanks for your reply!

**Comment by CSCYQJ** [comment]
Sorry to bother, it seemd that the script for Task025_LymphNodes was still missing. I'd like to know when it will be uploaded.
Thanks for your help!

**Comment by rongzhao-zhang** [comment]
Same request here. Could you make the preparation script available? Thank you so much!
