### ISSUE TITLE
[Question]read data, load_case_from_list()

### ISSUE THREAD

**Issue by yangqiqi** [MIC-DKFZ/nnDetection#115]
Thank you for your work and reply, and I have a questions to discuss with you:
In this function :nnDetection.nndet.io.load.load_case_from_list() 
Why do we need to change it? Do all images need to do this？

![ques](https://user-images.githubusercontent.com/12292180/200772350-0d227944-aa66-4199-8a45-54861f9594e8.png)

**Comment by mibaumgartner** [comment]
Yes, the saved information refers to the numpy data, Simple ITK reverses the order of axis when converting the sitk.Image into a numpy array. As a consequence the size and spacing extracted from the sitk Image needs to be reversed as well.

**Comment by yangqiqi** [comment]
Yes, I can't agree with you more.On my data set, 
"np.array(data_itk[0].GetSize())" ,the order of axes returned by this key is (x,y,z),for example, (512,512,369)
"sitk.GetArrayFromImage(d)", the order of axes returned by this API is (z,y,x), for example, (369,512,512)
Therefore, I have made two changes in the part, as shown in the picture, Is this correct?

![2](https://user-images.githubusercontent.com/12292180/201031764-fe197bc3-02cd-42e0-9c5d-5f6c0f9432f0.png)

**Comment by mibaumgartner** [comment]
Dear @yangqiqi ,

nnDetection will automatically handle the transposing (and revert the transposing for final predictions) for you, there is no need to make those changes to the code. It determines the z axes by checking for axes with the highest spacing (usually resulting in the axes with the lowest resolution).

The code can be found here: https://github.com/MIC-DKFZ/nnDetection/blob/1044ace5340b2a07bf9f9d5f92681f712cc0d2b4/nndet/planning/experiment/v001.py#L105-L123

The forward permutation is applied during the preprocessing while the backward permutation is applied in the postprocessing of the predictions (by the ensembler class).

Note: There are only two limitations -> 1) The training dataset should have the same axes format for all images i.e. in your case, all images should be in x, y, z (according to sitk). 2) If nndet_predict is used on test data, the test data needs to be in the same format as the training data, i.e. if the training data is in x,y,z the test data should be in x,y,z as well.

**Comment by yangqiqi** [comment]
I see. Thank you very much for your reply.

**Comment by yangqiqi** [comment]
I see. Thank you very much for your reply.
