### ISSUE TITLE
change network

### ISSUE THREAD

**Issue by yangqiqi** [MIC-DKFZ/nnDetection#120]
First of all, thank you for your work. I have a question for you. I want to change the network structure and take maskrcnn instead of taking the RetinaUnet. What should I change?

**Comment by mibaumgartner** [comment]
Dear @yangqiqi ,

the model can be exchanged by writing a custom module for it, e.g. the RetinaU-Net module is locatd here: `https://github.com/MIC-DKFZ/nnDetection/blob/main/nndet/ptmodule/retinaunet/base.py` . Unfortunately, Mask R-CNN is not implemented in the current version of nnDetection. 

Best,
Michael

**Comment by mibaumgartner** [comment]
Since there was no update for some time I’ll close this Issue for now.
Please feel free to reopen this Issue if the problem persists or open a new one.
