### ISSUE TITLE
[Question] do another training on another GPU

### ISSUE THREAD

**Issue by xaratustrah** [MIC-DKFZ/nnDetection#123]
### :question: Question

During training and other GPU activities, it is a pity that one of my GPUs is on 100% while others are just sitting around. I was wondering if it is somehow possible to start a different training on a different data set, from a different shell, on say GPU2, and another on GPU3 and so on. In Docker I think it would be possible to create several instances managed by `--gpu` but is it possible to do it using the installation method? i.e. somehow tell the code to use a different GPU?
Many thanks!

**Comment by mibaumgartner** [comment]
Dear @xaratustrah ,

you can start multiple training on the same machine via `CUDA_VISIBLE_DEVICES=1 nndet_train ...`. 

Best,
Michael
