### ISSUE TITLE
[Question] Speeding up training super slow

### ISSUE THREAD

**Issue by xaratustrah** [MIC-DKFZ/nnDetection#124]
### :question: Question

I checked the FAQ section in the readme about speeding up, not sure what else can be done. Currently training on **example dataset** `000D3` is extremely slow, but not stuck, it works but, I am more than 38 hours still 80% of Epoch 2. All hard disks are SSD. GPU is 100% all the time, and `htop` shows `nndet_train --sweep` across all 12 CPUs. `det_num_threads` is 12 now, which is the number of available CPUs: `lscpu | egrep 'Model name|Socket|Thread|NUMA|CPU\(s\)'` gives:

```
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              1
Socket(s):                       2
NUMA node(s):                    2
Model name:                      Intel(R) Xeon(R) CPU E5-2643 v4 @ 3.40GHz
NUMA node0 CPU(s):               0,2,4,6,8,10
NUMA node1 CPU(s):               1,3,5,7,9,11
```

Pytorch version is 1.13, so the speedup should be in it. But is there a independent way of checking that?
Any ideas for speedup are welcome.

I also get many warnings of this type:

```
WARNING WarmUp was stepped too often, 4000 but only 4000 were expected!
```

many thanks!

**Comment by mibaumgartner** [comment]
Dear @xaratustrah ,

that is definitely to long, I summarised quite a lot of information in this Issue: https://github.com/MIC-DKFZ/nnDetection/issues/11 and in the readme FAQ "Slow training speed". It sounds rather strange that the GPU would be pinned at 100% all the time and the training is slow. What kind of GPU are u using? (i.e. does it have Tensor Cores?) 

Note: for the example dataset you can get away with only 1 epoch or so and already achieve near perfect results, just to avoid spending too much time there. 

Regarding the warning: the LR scheduler warning can be ignored.

**Comment by xaratustrah** [comment]
ok, I see. I have Tesla K80 `sm_37`, with Kepler core, which as far as I could see on the internet, does not have Tensor Cores yet, since apparently TCs are first introduced with the Volta series. So maybe I need to upgrade the hardware to Ampere. So that might be the reason why things are going slowly. ☹️

For now I will stop the training after Epoch 2, so that I can play with the test dataset.

**Comment by mibaumgartner** [comment]
Ah, I see, the problem is that the GPU is rather "slow" while having quite a lot of memory. This leads to extremely large patch sizes (i.e. slow training) with a rather "slow" gpu (i.e. even slower training). For the example dataset it would be possible to manually set the patch size to [128, 128, 128] which should speed up the training significantly.

**Comment by xaratustrah** [comment]
thanks for the suggestion. Is it possible to do that by overwriting in `nndet/conf/train/v001.yaml`, or how exactly do you suggest to proceed?
