### ISSUE TITLE
[Question] 2D --> 3D dataset

### ISSUE THREAD

**Issue by xaratustrah** [MIC-DKFZ/nnDetection#125]
### :question: Question

I understand in `readme.md` you write that 2D data sets are not supported in the first release. I was nevertheless trying it, similar to [this approach](https://homepage.caoz.top/post/training-2d-nnunet-with-personal-dataset/), I created my own dataset and nifti files accordingly, i.e. they are 3D but contain only one slice. The first time `nndet_prep` complains is on [this line](https://github.com/MIC-DKFZ/nnDetection/blob/main/nndet/planning/architecture/boxes/base.py#L449) where it tries to get the dimensions of a `tensor([], size=(0, 3))` which fails with the `torch` error:

```
IndexError: max(): Expected reduction dim 0 to have non-zero size.
```

basically one can reproduce this error in a simple way like this:

```
import torch
a = torch.empty((0, 3))
a.max(dim=0)
```

my question is, regarding 2D data, is this approach (giving 2D arrays a higher dimension) tenable for usage of 2D datasets with nnDetection and only minor fixes are needed, or is there much more under the hood that would come to light one error after the other?

I am not really an expert on this, and maybe this is too simplistic, but more specifically, would it be possible to change the `stack` call on [this line](https://github.com/MIC-DKFZ/nnDetection/blob/a49cfed5c370d2e9fa5bcf9a4a7e32625145f588/nndet/core/boxes/ops.py#L392) in order to always return a 3D slice, in order to fix the issue with 2D datasets?

I was really hoping to use nnDetection with my 2D dataset.

Many thanks!

**Comment by mibaumgartner** [comment]
Dear @xaratustrah ,

to get nnDetection working on 2D data several changes are required, mostly in the preprocessing and postprocessing (the core is fully compatible with 2D and 3D data). Nevertheless, some things won't work as expected if you use "pseudo" 3D data without modifying the rules, e.g. the number of anchors will be significantly too high with the current configurations (due to the third dimension).

**Comment by xaratustrah** [comment]
Thanks for your comment, and it is a great news that the core of nnDetection is compatible with 2D data. There are many 2D applications, where I guess nnDetection would be a very suitable tool. I was wondering, whether it is possible to spot / identify the specific "construction sites" in the code that are related to this matter, so that, after fixing, maybe a not optimized but at least overall working example can be carried through the whole chain?

I am not an expert, but I would be curious to look into the specific locations inside the code...maybe I understand ...

**Comment by mibaumgartner** [comment]
Since this is considered out of scope of the current release of nnDetection, I'll close this Issue for now.
