### ISSUE TITLE
Resume training

### ISSUE THREAD

**Issue by vankhoa21991** [MIC-DKFZ/nnDetection#13]
Hello, is it possible to interrupt the training then resume it?

Thanks

**Comment by vankhoa21991** [comment]
Nevermind, I found the setting in conf/config.yaml

**Comment by BelieferQAQ** [comment]
> Nevermind, I found the setting in conf/config.yaml

hi，How do you operate it? What instructions are used?

**Comment by vankhoa21991** [comment]
You can use -o train.mode=resume

**Comment by BelieferQAQ** [comment]
> You can use -o train.mode=resume

Hello, excuse me, I originally planned to train 50 epochs, but I want to suspend the training after 42 epochs. How can I use the best weight currently saved to predict and evaluate fold0? How should the relevant instructions be written? thank you

**Comment by mibaumgartner** [comment]
You can use nndet_sweep and nndet_predict to sweep/evaluate and predict the model. Make sure to move the last model to a different folder before doing so.
