### ISSUE TITLE
how these coordinates aranged in pred_boxes in val_predictions?

### ISSUE THREAD

**Issue by leetesua** [MIC-DKFZ/nnDetection#132]
original_size_of_raw_data: array([ 82, 512, 512]),
my pred_boxes in pkl file be like:
array([[ 51, 225,  80, 291, 144, 199],
       [  0, 192,  32, 291, 321, 397],
       [  1, 223,  33, 295, 345, 394],
       [ 17, 220,  47, 307, 337, 406],
       [ 33, 271,  55, 316, 333, 376], ...
how to order zmin, zmax, xmin, xmax, ymin, ymax, accordingly?

**Comment by mibaumgartner** [comment]
Sorry for the delay, I was on vacation.

Given an image in x,y,z format the bounding box coordinated are in the format x_min, y_min, x_max, y_max, z_min, z_max.

**Comment by DSRajesh** [comment]
Hello
In the above example bounding box coordinates,  array ([[ 51, 225, 80, 291, 144, 199]])  ,   

the coordinates are zmin, ymin, zmax, ymax, xmin, xmax          right ?

Thank you

Rajesh

**Comment by mibaumgartner** [comment]
Hi Rajesh,

yes, since the array is in z,y,x format and not in x,y,z :) 

Best,
Michael
