### ISSUE TITLE
[Question] Instance lost

### ISSUE THREAD

**Issue by machur** [MIC-DKFZ/nnDetection#134]
Hi @mibaumgartner, I encountered the following error during planning step:

2022-12-30 23:45:03.864 | WARNING  | nndet.planning.properties.instance:instance_class_and_region_sizes:213 - Instance lost. Found {1: 0, 2: 0, 3: 0, 4: 0, 5: 0} in properties but [2 3 4 5] in seg of PATIENT 5223_VISIT 2.

I've inspected that particular cropped segmentation manually and it looks just fine, blob containing component "1" is present:
![image](https://user-images.githubusercontent.com/4650515/210117294-f6c488b1-728d-4a3b-8f22-4f21f4f56289.png)

As far as I understand, this error is raised before resampling, so the component "1" should not disappear (it's the smallest blob in the image though). Also I think that a different message is shown when a blob is lost during resampling. Would you please advice? Is there another input file that I can analyze here before I start a step-by-step debugging?

**Comment by mibaumgartner** [comment]
Dear @machur ,

Sorry for the delay, I was on vacation. Happy to see that the problem was resolved, if anything else comes up, just let me know.

Best,
Michael
