### ISSUE TITLE
[Question] VersionConflict

### ISSUE THREAD

**Issue by EvelyneCalista** [MIC-DKFZ/nnDetection#136]
Dear Dr. Jaeger,

it is wonderful project, I have some questions:
1. I would like to try with my own dataset and already build the docker container. however when I run _**nndet_prep**_ i got the version conflict error. May I ask how can i address this issue?
_raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (packaging 20.4 (/opt/conda/lib/python3.8/site-packages), Requirement.parse('packaging>20.9'), {'shap'})_

2. For research purpose, would the MedicalDetection Toolkit still can be used? Thank you so much.

**Comment by mibaumgartner** [comment]
Dear @EvelyneCalista ,

Sorry for the delay, I was on vacation. I pushed an update to the requirements of the dockerfile which updates the PyTorch Version. Your error might be unrelated though, could provide some additional information e.g. did you use the Dockerfile? Please post the entire log and error message

Regarding your second point: the MedicalDetectionToolkit can still be used but we can not offer extensive support via Issues or provide significant updates (e.g. in terms of models or newer pytorch releases). Actively maintaining a repository is connected with quite a lot work and unfortunately we are missing the capacities to maintain two detection repositories over an extended amount of time. 

Best,
Michael

**Comment by mibaumgartner** [comment]
To my knowledge this should have been solved and since there was no update, I'll close the issue for now. If the problem still persists, please reopen this Issue.
