### ISSUE TITLE
Data Preparation Problem

### ISSUE THREAD

**Issue by dmoyer357** [MIC-DKFZ/nnDetection#138]
### :question: Question

Hello,

I firstly wanted to prepare Task0078_Hepatic_Vessel dataset  for training  but  I  always faced ERROR: Unable to determine ImageIO reader, (RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:105:sitk::ERROR: Unable to determine ImageIO reader for "/home/Desktop/nnDetection/det_data/Task008_HepaticVessel/raw/imagesTr/._hepaticvessel_001.nii.gz") (I faced similar problem in Pancreas dataset, too). In home/Desktop/nnDetection/det_data/Task008_HepaticVessel/raw/imagesTr/  directory, there is no ._hepaticvessel_001.nii.gz file. Why is it always looking for it? 

Thank you,

**Comment by mibaumgartner** [comment]
Dear @dmoyer357 ,

can you run `ls -a` in the folder? or activate hidden files? I suspect there are hidden temp files in there which are not shown but are actually there and picked up by python.

Best,
Michael

**Comment by dmoyer357** [comment]
Thank you, you are right, with removing hidden files it worked! However, this time I faced unpacking problem.(python3 utils.py - unpack ${det_data}/Task007_Pancreas/preprocessed/D3V001_3d/imagesTr 6) . It just only gives environments  (system, nndetection, pytorch information )not unpacking. Because of this, I could not  train, it gives unpacking warning.

Where have I been stuck into? 

Thank you,

**Comment by mibaumgartner** [comment]
Can you post the exact command you are running and the full error log?

**Comment by dmoyer357** [comment]
> 

![Screenshot from 2023-01-23 12-07-45](https://user-images.githubusercontent.com/123125138/214002162-27af3a36-4303-4a9d-bf0f-7c17377d988a.png)

**Comment by mibaumgartner** [comment]
`python utils.py` will execute the

```
if __name__ == "__main__":
     #something
```

part of the script. Is there a specific reason not to use the nndetection entrypoint `nndet_unpack`? That one should work fine

**Comment by dmoyer357** [comment]
I used it for the data_generator nndet_example. But  I have encountered problem in Hepatic Vessel Dataset  by doing like this. Because of this,  I did similar way used in preprocess section( like python3 preprocess.py Task008_HepaticVessel ( it worked) and I went on doing like this) .  I attached the problem  I always I faced  while I had been using nndet_unpack . 
![Screenshot from 2023-01-23 13-38-24](https://user-images.githubusercontent.com/123125138/214019541-674d06bf-5367-4206-81fb-01b6da583bef.png)

I could not see any issue about this here and have no idea to overcome it (in spite of stackoverflow steps doing).

Thank you for your return,

Best;

**Comment by mibaumgartner** [comment]
Hmm, the error indicates some version problem with the packages but it worked correctly for the example dataset?  Are there any differences wrt to your environment between those experiments?

Alternatively, you can also modify the part I have linked above to call the respective function manually and use the python execution command.

**Comment by dmoyer357** [comment]
nndet_example  and other steps(preprocess, unpack and training steps) worked in docker root. (as a root@80a8f51d88e7:/opt/code/nndet# ). But I could not copy HepaticVessel dataset  to docker nndetection:0.1 /opt/data. (docker cp command worked but in that folder there was no data.I could not overcome it.) Because of this, I thought of working with sudo in nnDetection folder. I created det_data, det_models folders, prepare and preprocessed data with python3 command. It  worked, but unpacking made me in trouble. 


Thank you, I hope it works.

**Comment by dmoyer357** [comment]
I could not understand. In docker opt/data , there is no data and consequently  i tried to copy data to the docker /opt/data folder. (It did not work when used full address that existed in desktop) In ıssues and  readme.md, there is no problem about this. Thus, I tried all ways in copy but failed. However, when implementing prepare and preprocess with sudo -s, I kept going on. Now I am trying to modify utils.py to run (I failed there,too but I will overcome.)

Thank you,

**Comment by mibaumgartner** [comment]
The error indicates that the installation failed and thus the operators are not available

I would recommend using the docker container

The readme contains the command to mount local folders into the docker container i.e. `-v ${det_data}:/opt/data` where ${det_data} is the path to the data and /opt/data is the path within the docker container (as such the first one should be changed and the second one is fixed)

**Comment by dmoyer357** [comment]
I had problem about prepare, preprocess section in docker (except nndet_example, it worked in all section). I could not  overcome it. Because of this, I did all sections with sudo -s and modification. (Errors are attached as screenshot). I am open for any recommendation for this. Because I am very confused in docker.

![Screenshot from 2023-01-24 13-33-12](https://user-images.githubusercontent.com/123125138/214270896-54d62911-cd33-4a94-9f43-2e708a25e241.png)
![Screenshot from 2023-01-24 13-33-21](https://user-images.githubusercontent.com/123125138/214270903-9726baa4-b585-4785-96cd-af2a00c83af0.png)


Thank you,

**Comment by mibaumgartner** [comment]
You updated the wrong part in the command, /opt/data and /opt/models should never be changes in that command. You need to replace `${det_data}` with the path (also create a folder for the models, otherwise they won't be saved):

```bash
docker run --gpus all -v /home/dell/Desktop/nnDetection/det_data:/opt/data -v /home/dell/Desktop/nnDetection/det_models:/opt/models -it --shm-size=24gb nndetection:0.1 /bin/bash
```

**Comment by dmoyer357** [comment]
Thank you. Training has been working.(I hope it keeps going on.)

Big wishes,
