### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by LuckyBrighter** [MIC-DKFZ/nnDetection#14]
### :question: Question

I used the script 'nndet/projects/Task016_Luna/scripts/prepare.py' to get the train and label format data, but I met the error  below:

File "prepare.py", line 64, in _create_mask
    mask = create_circle_mask_itk(data, centers, rads, ndim=3)
  File "/opt/code/nndet/nndet/io/itk.py", line 71, in create_circle_mask_itk
    return copy_meta_data_itk(image_itk, mask_itk)
  File "/opt/code/nndet/nndet/io/itk.py", line 87, in copy_meta_data_itk
    raise NotImplementedError("Does not work!")
NotImplementedError: Does not work!

After runing the script, I got the train image data with the right format.,but got none in the dir  "/opt/data/Task016_Luna/raw_splitted/labelsTr".

The question is how can I get  the label data in the right format , is there any other ways?
I used the docker to install the nndet.

**Comment by mibaumgartner** [comment]
Hi @LuckyBrighter ,

I'll update the script today, sorry for the delay. I deprecated the function some time ago and forgot to replace it in the script.

Best,
Michael

**Comment by LuckyBrighter** [comment]
Alright,thanks for your reply!

**Comment by mibaumgartner** [comment]
Should be fixed with cb4804025e002e74cb328af82c3b2df4bc6fd3cb .
