### ISSUE TITLE
[Question] label jason file format error

### ISSUE THREAD

**Issue by hongzhiwang3** [MIC-DKFZ/nnDetection#141]
### :question: Question

I am trying to run the code on the Task010_Colon data. The preprocessing script in Task001_Decathlon/ does not include the code for generating the .jason file for each training segmentation file. I generated those .jason files based on the description in "Label Format" section. When I ran "python preprocess.py Task010_Colon" it gave the following error message. 

  File "/opt/code/nndet/nndet/utils/check.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "preprocess.py", line 388, in main
    check_data_and_label_splitted(
  File "/opt/code/nndet/nndet/utils/check.py", line 179, in check_data_and_label_splitted
    raise ValueError(f"Expected {mask_info_path} to be a raw splitted "
ValueError: Expected /opt/data/Task010_Colon/raw_splitted/labelsTr/colon_001.json to be a raw splitted mask info path but it does not exist.

It seems that some other data is expected in the .jason file, which is not described in the "Label Format" section. Do you have any suggestions on how to address this issue? Or could you recommend a script for generating the jason file for each training segmentation?

Thanks,
Hongzhi Wang

**Comment by mibaumgartner** [comment]
Dear @hongzhiwang3 ,

the script will only prepare the dataset.json and the data. The labels (inlcuding the jsons) can be downloaded from the link written in the readme. 

Best,
Michael
