### ISSUE TITLE
[Question] nndet prep error

### ISSUE THREAD

**Issue by EvelyneCalista** [MIC-DKFZ/nnDetection#149]
### :question: Question

Hi @mibaumgartner , I run nndet prep, however I cannot find the source of the error.
my task is prediction with two classes 0 or 1.

  _File "/opt/conda/bin/nndet_prep", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_prep')())
  File "/opt/code/nndet/nndet/utils/check.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/opt/code/nndet/scripts/preprocess.py", line 406, in main
    run(OmegaConf.to_container(cfg, resolve=True),
  File "/opt/code/nndet/scripts/preprocess.py", line 335, in run
    run_planning_and_process(
  File "/opt/code/nndet/scripts/preprocess.py", line 162, in run_planning_and_process
    plan_identifiers = planner.plan_experiment(
  File "/opt/code/nndet/nndet/planning/experiment/v001.py", line 43, in plan_experiment
    plan_3d = self.plan_base_stage(
  File "/opt/code/nndet/nndet/planning/experiment/base.py", line 234, in plan_base_stage
    architecture_plan = architecture_planner.plan(
  File "/opt/code/nndet/nndet/planning/architecture/boxes/c002.py", line 127, in plan
    res = super().plan(
  File "/opt/code/nndet/nndet/planning/architecture/boxes/base.py", line 340, in plan
    super().plan(
  File "/opt/code/nndet/nndet/planning/architecture/boxes/base.py", line 219, in plan
    self.plot_box_area_distribution(**kwargs)
  File "/opt/code/nndet/nndet/planning/architecture/boxes/base.py", line 139, in plot_box_area_distribution
    _boxes = np.concatenate(
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate_

my metadata is like this, i am not sure if this has issue related with this metadata info.

 meta = {
        "name": "xxx",
        "task": "Task000",
        
        "target_class": None,
        "test_labels": False,

        "labels": {"0": "xxx","1":"xxx"},
        "modalities": {"0": "xxx"},
        "dim": 3,
    }

Thank you for your help

**Comment by EvelyneCalista** [comment]
Hi i found my error, it turns out my mask is not binary, hence cannot catch the boxes.
Thank you

**Comment by mibaumgartner** [comment]
Dear @EvelyneCalista ,

Your masks are not supposed to be binary: The mask should provide indices for each object (i.e. for three objects the mask should have entries 0 for background; 1,2,3 for the objects). The corresponding json file maps the objects to their classes.

I'm currently trying to reproduce the Issue by running nndet with a new env on the example data. 
Can you reproduce the error with example data?

Best,
Michael

**Comment by EvelyneCalista** [comment]
Dear @mibaumgartner 

Thank you for your help. 
my mask was value ranging [0,1] when the issue is produced.
i'll try with the example data.

May I ask one more question, i am not sure on how i define the _target_class_ and _test_labels_ in the metadata info.
for classification with two classes, can I leave those two params with None?


Evelyne

**Comment by mibaumgartner** [comment]
Yes, those parameters are optional. `test_labels` just indicates if there is a test which is labelled as well (and thus should be evaluated at some point). Since nnDetection is used in challenges as well, access to the test labels is not given in those scenarios. If you have more than one class and want to perform a patient level evaluation the target_class can be used to specify the class of interest (e.g. used for tumor detection where malignant and benign lesions might be present but we are only interested in the malignant class for patient level performance).
