### ISSUE TITLE
[Bug] Padding around boundaries and restoring feature map

### ISSUE THREAD

**Issue by mgeessinck** [MIC-DKFZ/nnDetection#155]
### :skull: Bug
Two bugs were identified during inference, using the do_seg=True flag (so using the segmentation ensembler).

_First bug_
When padding is necessary (patch size is bigger than the whole case), the image is padded with the _padded_crop method (patching.py). Three values are returned: 1) the padded crop, 2) the origin of the original crop and 3) the clipped crop. This clipped crop is stored for each tile.

Later on, the padding that is used at the borders, is removed in the crop_to_case_boundaries method. This method returns two variables: **seg** and **case_crop**. The **seg** variable is created with a crop_slicer and this crop_slicer is defined by the crop_start and the crop_stop, which depend on the clipped_crop size.

The crop_start is calculated as follows:
`crop_start = max(0, 0 - (c.start - 0))  # 0 added for completeness of pattern
`
in which c.start is the start of the clipped_crop.
For all tiles in the image, the value of crop_start will always be zero, because c.start of the clipped_crop can never be a negative value. Therefore the max(0, 0 - c_start) will always be 0. 
The crop_stop is calculated as follows:
`crop_stop = min(seg.shape[dim + 1], seg.shape[dim + 1] - diff_stop)`

These definitions of crop_start and crop_stop resulted in the variable **seg** that has a size equal to the patch size, whereas the variable **case_crop** has a smaller size. The size of **case_crop** is equal to the part of the patch that lays within the image boundaries (which is smaller than the patch size at the boundaries were padding is performed). As a result, line 176 of segmentation.py: `(self.model_results[case_crop] += seg)` raised the following error: 
`RuntimeError: The size of tensor a (141) must match the size of tensor b (224) at non-singleton dimension 3. `

For clarification, in the case of this error, we had an input image array [channels, z, y, x] of size (3, 63, 408, 391) and the patch size is (3, 64, 224, 224). This means that padding is needed in the z-direction. For the first tile, the tile crop was defined as: [-1:63, -69:155, -83:141]. Therefore, the resulting **clipped crop** was: [0:63, 0:155, 0:141]. Within the crop_to_case_boundaries the following values were obtained per dimension:
dim 1: crop_start = max(0, -0) = 0 and crop_stop = 64
dim 2: crop_start = max(0, -0) = 0 and crop_stop = 224
dim 3: crop_start = max(0, -0) = 0 and crop_stop = 224

This results in a size of (64, 224, 224) for **seg**, whereas **case_crop** has a size of (63, 155, 141), because case_crop represents the part of the tile that falls within the image boundaries.

Performing the following operation: self.model_results[case_crop] += seg will raise an error since the sizes differ. 

The bug is fixed by letting the _padded_crop method return the **original crop** [-1:63, -69:155, -83:141] instead of the **clipped crop**. In that case, the following values will be obtained for each dimension in the crop_to_case_boundaries method:
dim 1: crop_start = max(0, 1) = 1 and crop_stop = 64
dim 2: crop_start = max(0, 69) = 69 and crop_stop = 224
dim 3: crop_start = max(0, 83) = 83 and crop_stop = 224
This results in a size of (64, 155, 141) for **seg**, and the **case_crop** still has the same size, so the operation self.model_results[case_crop] += seg will no longer raise an exception. 

_Second bug_
When restoring the featuremap (restore_fmap in restore.py), an index error was raised in line 124:
`IndexError: only integers, slices (':'), ellipsis ('...'), numpy.newaxis ('None') and integer or boolean arrays are valid indices`
This error is caused by a dimensionality mismatch between the applied slice and the tmp array. 
Original code:
```
_slices = [...] + [slice(b[0], b[1]) for b in crop_bbox]
tmp[_slices] = fmap_old_spacing
```
Code fixing the error:
```
_slices = [slice(b[0], b[1]) for b in crop_bbox]
tmp[(..., *_slices)] = fmap_old_spacing
```

### Environment

How was nnDetection installed [`docker` | `source`]:
Source

Environment Information:
```text
----- PyTorch Information -----
PyTorch Version: 1.11.0+cu102
PyTorch Debug: False
PyTorch CUDA: 10.2
PyTorch Backend cudnn: 7605
PyTorch CUDA Arch List: ['sm_37', 'sm_50', 'sm_60', 'sm_70']
PyTorch Current Device Capability: (6, 1)
PyTorch CUDA available: True


----- System Information -----
System NVCC: nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0

System Arch List: None
System OMP_NUM_THREADS: 1
System CUDA_HOME is None: False
System CPU Count: 40
Python Version: 3.8.0 (default, Nov  6 2019, 21:49:08)
[GCC 7.3.0]


----- nnDetection Information -----
det_num_threads None
det_data is set True
det_models is set True


```

**Comment by mibaumgartner** [comment]
Dear @mgeessinck ,

thank you for the very detailed bug report, I'll look into this in more detail and update you as soon as I can.

Best,
Michael
