### ISSUE TITLE
crop the tumor region using the bounding boxes

### ISSUE THREAD

**Issue by sovanlal** [MIC-DKFZ/nnDetection#156]
Hi @mibaumgartner,

I am recently getting good performance on one of my datasets [AP@0.1 >0.90]. However, I have a quick question

I want to crop the tumor region using the bounding boxes that I am getting. I ran nndet2_boxesnii to visualize the boxes. However, it gives me multiple boxes as shown below.

![image](https://user-images.githubusercontent.com/50425154/226420828-72694ab9-f60c-4caa-829f-6bfb0bc15410.png)

a. Are these scores the confidence probabilities that the boxes contain an object? 
b. I am assuming the coordinates are zmin, zmax, xmin,xmax and ymin,ymax; correct?
c. How to get a single unified bounding box among multiple boxes?

**Comment by mibaumgartner** [comment]
Hi,

a) yes
b) Given an z,y,x image in the nifty format, it will be x,y,z after converting it to a numpy array with SimpleITK (which nnDet uses) => the bounding boxes will be in x_min, y_min, x_max, y_max, z_min, z_max format
c) This is something you probably need to investigate yourself based on your dataset. In general, there is an unknown number of objects in object detection and the goal is to predict all the objects => i.e. generating multiple predictions is the primary purpose of nndetection

**Comment by mibaumgartner** [comment]
There is no built in way to that right now, but you could implement something yourself. If the tumors tend to be rather larger one, it is beneficial to use the low res model if not already done (if it was triggered).

**Comment by sovanlal** [comment]
@mibaumgartner ,

I have a quick question. I was using a different dataset for inference by placing it inside raw_splitted/imagesTs folder. Now , I want to do inference on a new dataset. However, when I replace the imagesTs with the new dataset and run nndet_predict, it's predicting both the datasets (i.e. repeating prediction on the older dataset as well). Is there anyway I can do inference only on the current dataset?

**Comment by mibaumgartner** [comment]
Good point, I think the inference will be redesigned in a future version to be completely folder based. 

There is a folder imagesTs in the {Your Task}/preprocesses/D3V001 folder, it contains the preprocessed versions of your current and probably your old data. Just delete your old data from there
