### ISSUE TITLE
About overwrite trained fold and sweep

### ISSUE THREAD

**Issue by eleo23-12** [MIC-DKFZ/nnDetection#157]
Hello,

In the training phase, -o exp.fold=1 overwrites trained fold 0,  -o exp.fold=2 overwrites  trained fold 1 and going on like this. In every trained fold, sweep section was implemented right after training.

Do we extra need to implement sweep section after all trained folds?

Best,

**Comment by mibaumgartner** [comment]
HI,

`nndet_consolidate` has a sweep option which should be used to find the final parameters

**Comment by eleo23-12** [comment]
> HI,
> 
> `nndet_consolidate` has a sweep option which should be used to find the final parameters

With -sweep_boxes? or -sweep_instances? 

Thank you for your return,

Best,

**Comment by mibaumgartner** [comment]
Currently, only `sweep_boxes` is available and should be used as noted in the readme. The folds should be fine, as you wrote, the default is 0. You can always check that fold0-4 folders exist in the training directory.
