### ISSUE TITLE
Question about the Dataset

### ISSUE THREAD

**Issue by linleoxdu** [MIC-DKFZ/nnDetection#158]
Hi! I'm a little confused about the dataset configuration. As a detection problem, it's normal to use bound box level labels. In your framework, mask labels are needed. For my own dataset, there is only bound box labels but not masks. Can I generate mask labels directly based on bound box labels? Or should I annotate mask labels manually?

**Comment by mibaumgartner** [comment]
Dear @linleoxdu ,

you are absolutely right, pure bounding box support might added at some point in the future as well but we are currently working towards other features. The segmentation approach was chosen for two reasons: 1) IO and augmentation framework don't have broad support for 3D images with bounding boxes 2) there is a lack of standardization with coarse annotations, e.g. while many datasets are annotated with segmentations there are different annotation strategies in the literature like boxes, circles etc. Supporting all of those would be infeasible but most of them can be converted into some kind of segmentation.

Yes, as long as the bounding boxes are not overlapping (which can not be reflected in segmentations), you can convert them to segmentations. Sometimes it is even beneficial to use some prior knowledge, e.g. lesions tend to round so using a circle might be an even better approximator.
