### ISSUE TITLE
How to visualize results?

### ISSUE THREAD

**Issue by vankhoa21991** [MIC-DKFZ/nnDetection#16]
Hello, do you have any function to visualize the validation results (bounding box prediction for example) on some images? 

Thanks

**Comment by mibaumgartner** [comment]
Hi @vankhoa21991 ,

`nndet_boxes2nii` converts boxes to a segmentation nifty file (bounding box location) + json file (for class and score prediction). Since the boxes can overlap but the 3D segmentations can not, there might be boxes that are suppressed or partly overlapped inside the visualization.

I did not find a tool that has an option to visualize 3D boxes from an input but I'm definitely open for suggestions if there is a better way out there :)

**Comment by vankhoa21991** [comment]
Thanks for your answer, it works well, when I check the mask extracted from the boxes, I have a few questions:

1/ What decides the color of the boxes, the color seems matched with the gt?
2/ In the foldx folder, there are always couple folders of _preprocessed, and without _preprocessed, what does it means?
3/ what is the difference between sweep prediction and val_prediction folder?

**Comment by mibaumgartner** [comment]
Hi @vankhoa21991 ,

1) nnDetection does not encode any color information so it only depends on the program you are using to visualize it.

2) Before training and inference, the data is preprocessed e.g. cropped to non-zero regions, resampling to target spacing. The _preprocessed folders contain predictions and results for the preprocessed data and are mainly added for debugging purposes. The folders without the preprocessed extension contain the "final" predictions and results in the original image space (so the cropping and resampling were reverted).

3) sweep_prediction saves additional state variables from the ensembler class to compute the outputs for different postprocessing parameters without rerunning the whole inference pipeline. val_prediction only contains the final predictions (as a consequence it is much smaller than the speed_prediction files)

Best,
Michael

**Comment by Derekabc** [comment]
> Thanks for your answer, it works well, when I check the mask extracted from the boxes, I have a few questions:
> 
> 1/ What decides the color of the boxes, the color seems matched with the gt? 2/ In the foldx folder, there are always couple folders of _preprocessed, and without _preprocessed, what does it means? 3/ what is the difference between sweep prediction and val_prediction folder?

@vankhoa21991 Hello, could you please provide any help on how to extract the segmentation and visualize it by the bounding boxes. Thank you so much!

**Comment by sovanlal** [comment]
Hi @mibaumgartner ,

I wanted to see the bounding box predictions as image (in .nii).

I saw in one of the threads that nndetbox2nii is the required command. Could you please let me know what should be the exact input that is required for the command?

**Comment by mibaumgartner** [comment]
Please refer to my answer in https://github.com/MIC-DKFZ/nnDetection/issues/139
