### ISSUE TITLE
About prediction and dataset.json

### ISSUE THREAD

**Issue by mclvnot** [MIC-DKFZ/nnDetection#160]
Hello,

After 5 fold training and consolidated, I wanted to predict dataset with _nndet_predict 006 RetinaUNetV001_D3V001_3d  --fold -1_  for consolidated results. However, I faced  _Found different values for fold, will overwrite 0 with -1_  warning.  It is normal for prediction with consolidated results that exists in consolidated folder.  Why do I get this warning?

Also, for multiclass and labelled dataset,  what  do i write "target class" and "labels"  in dataset.json? or  does  nndetect  support multiclass?

Best,

**Comment by mclvnot** [comment]
Thank you!

Could we convert  prediction results (zmin, zmax, xmin, xmax, ymin, ymax) to 2D predictions?

Best,

**Comment by mclvnot** [comment]
Also, I want to ask about evaluation metrics. In test results, I take care of AP_IoU_0.10_MaxDet_100.  Intersection over union threshold is 0,1 but is confidence score threshold is 0?   


Best,

**Comment by mibaumgartner** [comment]
The evaluation does not apply any confidence threshold but there is a maximum of 100 predictions per image. There might a confidence threshold in the model though, since sometimes it can boost performance before running the weighted box clustering
