### ISSUE TITLE
Sir, Excuse me, how about nnDetection compared with yolo v5 or v7?

### ISSUE THREAD

**Issue by xh542428798** [MIC-DKFZ/nnDetection#161]
I was using nnUnet, it is really great! 
Now I want to detect the medical lesions, but the paper and model was 3 years ago, I wonder how about nnDetection compared recent most famous model yolo (v5 or v7)？Do you tested them with yolo？

**Comment by mibaumgartner** [comment]
YOLOv5 and v7 are models from the natural image processing domain and thus primarily design for natural images. nnDetection in contrast is designed for volumetric (3D) detection and thus a direct comparison might be difficult. From my experience, translating architectures/improvements from natural images to medical images is rather difficult and rarely produces improved results.

**Comment by xh542428798** [comment]
> YOLOv5 and v7 are models from the natural image processing domain and thus primarily design for natural images. nnDetection in contrast is designed for volumetric (3D) detection and thus a direct comparison might be difficult. From my experience, translating architectures/improvements from natural images to medical images is rather difficult and rarely produces improved results.

I get it, thank you
