### ISSUE TITLE
[Question]Failed with env error

### ISSUE THREAD

**Issue by puppy2000** [MIC-DKFZ/nnDetection#163]
### :question: Question

![image](https://user-images.githubusercontent.com/55677296/230720756-0b25b71e-e433-489b-863e-b5ba79919e52.png)
When I try to install nndet(!pip install -e .) an error occured.
I wonder if it's because the mismatch of PyTorch CUDA and NVCC CUDA.
Please give me some advice,thanks a lot!

**Comment by mibaumgartner** [comment]
There is only a minor version mismatch between nvcc and pytorch which usually works. CUDA_HOME is set to something, please double check that the version where cuda home points to is also compatible.
