### ISSUE TITLE
what does this error mean after "pip install -e . "   ?

### ISSUE THREAD

**Issue by DSRajesh** [MIC-DKFZ/nnDetection#165]
while running the following code snippet:

import torch
import nndet._C
import nndet

found this error below:

ImportError: /data4/nnDetection4/nndet/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _Z8nms_cudaRKN2at6TensorES2_f

May In know please ?

**Comment by mibaumgartner** [comment]
This indicates some kind of problem during the installation, please refer to the FAQ section for some help.

**Comment by mibaumgartner** [comment]
continued in https://github.com/MIC-DKFZ/nnDetection/issues/166
