### ISSUE TITLE
TypeError: resize_segmentation() got an unexpected keyword argument 'cval'  while "nndet prep"

### ISSUE THREAD

**Issue by DSRajesh** [MIC-DKFZ/nnDetection#167]
I was trying to execute 

python scripts/preprocess.py 116   -np  4 -npp 3

and got the following error log
![image](https://user-images.githubusercontent.com/60175495/232392475-0555685d-49ed-43d2-8eb5-4304d574babc.png)

requirements.txt is like this

may I please know why this happened?
two days back I cloned nndetection (means I had pulled the recent master).

**Comment by mibaumgartner** [comment]
The argument was deprecated in an older version of nnunet and batchgenerators, I think the version should have been fixed on the github master by now. Can you post the version of these two packages so I can reproduce the Issue? (you can check the versions via `pip list`)
