### ISSUE TITLE
[Question] What is the purpose of "crop to nonzero region" ?

### ISSUE THREAD

**Issue by duchieuvn** [MIC-DKFZ/nnDetection#169]
### :question: Question

```
def create_nonzero_mask(data: np.ndarray) -> np.ndarray:  

    nonzero_mask = np.max(data != 0, axis=0)
    nonzero_mask = binary_fill_holes(nonzero_mask.astype(bool))
    return nonzero_mask
```

Hi everyone and many thanks to Michael Baumgartner for your dedication.
I have a question:
Why do we need to remain the zero (data != 0) inside the mask ? Why don't we just leave it to all ones (1) ?

**Comment by mibaumgartner** [comment]
The mask is used to perform a cropping in a subsequent step to remove potential zero borders. This can happen in some MRI datasets and just slows down training (since background patches are sampled randomly and with large 0 borders many patches could contain zeros) and costs memory.
