### ISSUE TITLE
Run validation on a test set

### ISSUE THREAD

**Issue by vankhoa21991** [MIC-DKFZ/nnDetection#17]
Hello, I trained 5 folds of the LUNA16 task, now I have another dataset, with images and mask, and I want to run evaluation on this dataset using the trained models. I ran nndet_predict, and obtain the folder test_predictions on those images, now I try to run nndet_eval and the code ask for masks processed in preprocessed/labelsTs.

How can I make this folder?

Thanks,

Van KHoa

**Comment by mibaumgartner** [comment]
Hi @vankhoa21991 ,

sorry for the late response. `labelsTs` is generated in the preprocessing stage by `nndet_prep`. I'll add an additional entry point so it is possible to generate them afterwards.

Best,
Michael
