### ISSUE TITLE
[Question]stop at sanity check

### ISSUE THREAD

**Issue by Zhang-JnQn** [MIC-DKFZ/nnDetection#170]
### :question: Question

I run '''nndet_train 000''' on the example data set。
It stop at sanity check。
![微信截图_20230423162317](https://user-images.githubusercontent.com/96648587/233828561-84779117-1016-4460-a7d7-ff3064e80af4.png)
I also check '''nndet_env'''
![微信截图_20230423162512](https://user-images.githubusercontent.com/96648587/233828644-263dd351-48d2-4407-ae16-ec3336dbd48e.png)
What should I do?

**Comment by Zhang-JnQn** [comment]
I saw FAQ & Common Issues and tried '''nndet_train 000 -o augment_cfg.multiprocessing=False'''. It didnt stop.
What should I do next?

**Comment by mibaumgartner** [comment]
Can you double check that there is a CPU load when you start the training i.e. the processes are started? How about the RAM consumption anything surprising going on there?
