### ISSUE TITLE
[Question] nnDetection suited for multilabel problem?

### ISSUE THREAD

**Issue by NoorBor** [MIC-DKFZ/nnDetection#177]
### :question: Question
Hi there! 

Thank you for the interesting nnDetection, great work! I am still figuring out the options and possibilities and wanted to ask if nnDetection is suited for a multilabel problem? My detected object is classified by two classes each consisting of three labels. So my object has two distinct characteristics. 
I did look into the classifier head and am thinking of adding an extra head. Is this possible in nnDetection and if so, are there any examples yet? 

Thank you very much in advance! 
Bests, 
Noor

**Comment by mibaumgartner** [comment]
Hey,

nnDetection is currently not designed to handle multi label problems. In order to get full support for it several modifications to the planning, training and inference steps need to be implemented => so it is probably a larger project to add all the necessary changes.

Best,
Michael
