### ISSUE TITLE
[Question] About prediction

### ISSUE THREAD

**Issue by yl3639** [MIC-DKFZ/nnDetection#178]
### :question: Question

Hi,
May I ask is there any way to speed up the predictions? I have images with resolutions about(500, 500, 300) and the prediction time of a case is about 4mins.

Thanks!

<img width="1892" alt="image" src="https://github.com/MIC-DKFZ/nnDetection/assets/20362958/5889d5de-070b-4c14-a58c-b798ddada67c">

**Comment by mibaumgartner** [comment]
Hi,

there are several parameters which can be adjusted to speed up the inference but smaller performance degredations are to be expected there (here in order from [likely] lowest perf impact to highest):
- disable test time augmentation
- use less models (inference only)
- decrease patch overlap while predicting 

Best,
Michael
