### ISSUE TITLE
pip install -e . error

### ISSUE THREAD

**Issue by MOMOANNIE** [MIC-DKFZ/nnDetection#183]
Hello，when I create a virtual environment and install torch, I run `pip install e`. The following problem occurs, what is going on?
```
conda create -n nndet python=3.8
conda install pytorch==1.12.0 torchvision==0.13.0 torchaudio==0.12.0 cudatoolkit=11.3
```
![image](https://github.com/MIC-DKFZ/nnDetection/assets/26375536/b9e2046f-490f-4e27-8ae3-73bc667b65be)

**Comment by mibaumgartner** [comment]
Hi,

sklearn updated its name and nnU-Net 1.6.6 uses the old naming. Can you try to change the nnU-Net version in the requirements file of nndetection to 1.7.1 and try to reinstall? 

Best,
Michael

**Comment by MOMOANNIE** [comment]
> 

Hmm, I have successfully reinstalled just now, but when running the `nndet_prep Task017` command, the following error occurs, how can I solve it?
![image](https://github.com/MIC-DKFZ/nnDetection/assets/26375536/8a89d151-ff4c-44e5-b26a-01ba373d8bdf)

**Comment by mibaumgartner** [comment]
Hi,

the error looks rather curious, could you start the script with CUDA_LAUNCH_BLOCKING=1. 

The error always comes up if an unexpected error is raised and the creation of the tensor fails, but I can not see the error in the log.
