### ISSUE TITLE
[Question] Difference between parameters in config.yaml

### ISSUE THREAD

**Issue by yl3639** [MIC-DKFZ/nnDetection#184]
### :question: Question

Hi,
May I ask whats the difference between parameter in config.yaml under augmentation:transforms:NoAug and augmentation:transforms:BaseMoreAug and what part of the code are related with this parameter?

<img width="190" alt="image" src="https://github.com/MIC-DKFZ/nnDetection/assets/20362958/8a486e17-2674-467e-b209-3d0b3e92121b">

<img width="212" alt="image" src="https://github.com/MIC-DKFZ/nnDetection/assets/20362958/99a70e19-5043-4d20-95c4-d2877c8b3e44">

Thanks!

**Comment by mibaumgartner** [comment]
Hi,

the transforms parameter defines the transformations which should be used for augmentation during training. Their implementation can be found here: https://github.com/MIC-DKFZ/nnDetection/blob/main/nndet/io/augmentation/bg_aug.py
