### ISSUE TITLE
[Question] Multiple inputs for model

### ISSUE THREAD

**Issue by BobdeThird** [MIC-DKFZ/nnDetection#188]
### :question: Question

Is there any way to make the model include multiple inputs?
And how should I format the data for training and validation?

**Comment by mibaumgartner** [comment]
Hi,

do you mean multiple input channels? By following the data format in the readme it is possible to specify multiple modalities which should be given to the network. Anything else (e.g. special inputs such as segmentations, spatial maps etc.) goes beyond the out of the box functionality of nnDetection and needs to be added by the user.

Best,
Michael
