### ISSUE TITLE
ModuleNotFoundError: No module named 'nndet._C'

### ISSUE THREAD

**Issue by DSRajesh** [MIC-DKFZ/nnDetection#189]
Hello

I recently changed the home folder location in an ubuntu system 22.04.    nndetection which was working fine stopped doing so and got the following error :

ModuleNotFoundError: No module named 'nndet._C'

on running     the script       python scripts/utils.py   found the following:

![image](https://github.com/MIC-DKFZ/nnDetection/assets/60175495/632f895d-e226-4902-b7f6-440d818e401c)

I need some help to fix this issue please

Regards
Rajesh D S

**Comment by mibaumgartner** [comment]
Dear @DSRajesh ,

I'm not sure what broke your installation. Could you try reinstalling it? 

Best,
Michael
