### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'glob'

### ISSUE THREAD

**Issue by merezhou** [MIC-DKFZ/nnDetection#192]
Hi,
 I also encountered this problem：
```
INFO Consolidate models
Traceback (most recent call last):
  File "/opt/conda/bin/nndet_consolidate", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_consolidate')())
  File "/opt/code/nndet/nndet/utils/check.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/opt/code/nndet/scripts/consolidate.py", line 159, in main
    consolidate_models(training_dirs, target_dir, ckpt)
  File "/opt/code/nndet/scripts/consolidate.py", line 46, in consolidate_models
    model_paths = list(sd.glob('*.ckpt'))
AttributeError: 'NoneType' object has no attribute 'glob'
```
However, I couldn't solve it. You said "If you want to run inference on the test set with a single fold, you can run nndet_predict and specify the fold parameter directly. Note: this will Ensemble all models in the training directory, i.e. the last and best one from that fold. Usually, nndet only uses the last one, which is handled by the consolidate function. To exclude the best model during inference, simply move it to a different folder." However, after running nnuet_predict, erro: found wrong number of training dirs[] in /opt/models/....(my dataset). Thus, I must solve the problem of nndet_consolidate.
I ran it in Fold0 and was successful.  Was it because of a conflict?

**Comment by mibaumgartner** [comment]
Consolidate won't work on a single fold, it is not designed for that purpose. 

Are the training directories at the specified path in the error?
