### ISSUE TITLE
[Question]Problem for server interruption, training task to continue

### ISSUE THREAD

**Issue by Lynclock** [MIC-DKFZ/nnDetection#198]
### :question: Question

Hi,
My linux server was interrupted, causing the training task to stop. Since I have been training for a long time, I do not want to start the training again. Can nndetection, like nnunet, have the command to choose to continue the training as follows:

"python /nnUNet/nnunet/run/run_training.py 3d nnUNetTrainerV2 121 all -c"

Does nndetection have the parameter "-c"?

Thank you!
Lynclock

**Comment by mibaumgartner** [comment]
nnDetection can continue training via the `-o train.mode="resume"` option.

**Comment by Lynclock** [comment]
Thank you.
