### ISSUE TITLE
[Question]About loss

### ISSUE THREAD

**Issue by alonelysnake** [MIC-DKFZ/nnDetection#199]
### :question: Question

In my task, I found the train loss<=0 after several epochs.  What caused this problem? Should I continue to train the model?

**Comment by mibaumgartner** [comment]
Yes, simply continue the training, it is normal that the loss becomes negative at some points. While most losses in nnDetection are positive, we simply use `-GIoU` as the loss instead of `1-GIoU` to avoid unnecessary computations -  the optimization target remains the same in both cases.
