### ISSUE TITLE
Questions regrdaing some parameters of control in v001.yaml

### ISSUE THREAD

**Issue by DSRajesh** [MIC-DKFZ/nnDetection#202]
Hello 

![image](https://github.com/MIC-DKFZ/nnDetection/assets/60175495/3debf49b-5cf7-48e5-bfed-8006d4d77419)
1. What is the importance of gpus in the above configuration setting of v001.yaml. Can we expedite the training by setting gpus=2  instead of 1, when we have two gpus in our training environment ?
2.  Also
![image](https://github.com/MIC-DKFZ/nnDetection/assets/60175495/f2d449a2-7aa6-4ca2-bd86-8d5cd3a16202)
what is the significance of "oversample_foreground_percent"   above ?  Is there a sweet spot value with which we can perform small diameter lung nodule detection training ?

Thanking you 

Rajesh

**Comment by mibaumgartner** [comment]
Hi @DSRajesh ,

we only experimented with gpus=1, changing that parameter might cause unknown problems (e.g. the evaluation is not run correctly, hard negative mining might not behave the same way as on a single GPU).

0.5 is quite a solid value which will oversample half of the batch as foreground. Reducing the value (e.g. to sample more background and reduce false positives) shows some training instability. Increasing it will likely improve your recall but induce more false positives.
