### ISSUE TITLE
[Question] NVIDIA GeForce RTX 4080 GPU is not yet supported in the Docker

### ISSUE THREAD

**Issue by Yasmin-Kassim** [MIC-DKFZ/nnDetection#204]
### :question: Question

Hi, I build and run the docker, everything looks right except a warning that stated Detected NVIDIA NVIDIA GeForce RTX 4080 GPU, which is not yet supported in this version of the container
ERROR: No supported GPU(s) detected to run this container

![image](https://github.com/MIC-DKFZ/nnDetection/assets/16782894/f44f69a1-ab00-4326-b37c-fa7c0d743d28)

Is there any solution to this problem ?

**Comment by mibaumgartner** [comment]
You could try to bump the base image in the docker image to a newer PyTorch version (make sure to keep the PyTorch Version below 2.0 since it is not yet supported in nnDetection).
