### ISSUE TITLE
There might be a bug in the norm_schemes.

### ISSUE THREAD

**Issue by xtj2020** [MIC-DKFZ/nnDetection#212]
https://github.com/MIC-DKFZ/nnDetection/blob/b2e0e4829f4dd9662a2ea7df219a658589716f57/nndet/preprocessing/preprocessor.py#L140

```
        self.norm_schemes = {
            "CT": self.normalize_ct,
            "CT2": self.normalize_ct2,
            "CT3": self.normalize_ct,
            "raw": self.no_norm,
        }
```

should be

```
        self.norm_schemes = {
            "CT": self.normalize_ct,
            "CT2": self.normalize_ct2,
            "CT3": self.normalize_ct3,
            "raw": self.no_norm,
        }
```

**Comment by mibaumgartner** [comment]
Dear @xtj2020 ,

good catch, CT3 normalisation scheme was deprecated since it was just an experiment -> I replaced it with the normalize_ct scheme to be on the safe side. Users should only use CT, raw or something completely different which will trigger the default norm. 

best,
Michael
