### ISSUE TITLE
[Question] The accuracy issue in reproducing the nndetection algorithm

### ISSUE THREAD

**Issue by pengwuke** [MIC-DKFZ/nnDetection#217]
Thank you very much for your work and contribution. We encountered issues when reproducing the nndetection algorithm on the Luna16 dataset. Initially, we tested the results on one fold and observed differences in accuracy compared to our expectations. Subsequently, we ran the algorithm on all folds and performed ensemble, but the results remained consistent. Could we have missed any steps leading to such outcomes? Any suggestions would be greatly appreciated.
![20231221104716](https://github.com/MIC-DKFZ/nnDetection/assets/30679728/d365d55e-3b98-4c33-bba8-91d9c943c0f1)

**Comment by mibaumgartner** [comment]
Dear @pengwuke ,

I guess your are referring to reproducing the numbers which are in the paper. 

The plots you show here are product by nndet_eval which (1) is based on bounding box IoU (2) does not include ignore locations. To get LUNA complient results you need to use the official LUNA evaluation script (as noted in the project readme of nnDet ;) ) which is provided by the challenge organisers, that will use (1) a center point based criterion (center point in radius of lesion) (2) includes a huge list of locations which are not counted as false positive predictions (please refer to their publication for more information on this). Especially (2) will boost the performance for low number of false positives and will allow for reproducing the numbers from our paper. 

Best,
Michael
