### ISSUE TITLE
[Question]The error of intall nndetection

### ISSUE THREAD

**Issue by jk-blacker** [MIC-DKFZ/nnDetection#22]
### :question: Question

Hi! Awesome work :)

Recently, I tried to install nnDetection with pip install -e .  , but I got  a problem:

ERROR: Command errored out with exit status 1:
     command: /home/sensetime/anaconda3/envs/nndet/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/sensetime/Documents/FHwork/code/nnDetection-main/setup.py'"'"'; __file__='"'"'/home/sensetime/Documents/FHwork/code/nnDetection-main/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/sensetime/Documents/FHwork/code/nnDetection-main/
    Complete output (106 lines):
......
ERROR: Command errored out with exit status 1: /home/sensetime/anaconda3/envs/nndet/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/sensetime/Documents/FHwork/code/nnDetection-main/setup.py'"'"'; __file__='"'"'/home/sensetime/Documents/FHwork/code/nnDetection-main/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command [output.](url)
![Screenshot from 2021-08-10 21-02-59](https://user-images.githubusercontent.com/54839089/128871868-74cf8965-e6c4-42a8-b7d7-063092badbd8.png)
![Screenshot from 2021-08-10 21-03-26](https://user-images.githubusercontent.com/54839089/128871887-2fda4a0e-7cec-4009-a663-ff0359b4b569.png)

Thank you for your help!

**Comment by mibaumgartner** [comment]
Hi @jk-blacker ,

please run `python utils.py` (with the activated environment) from the `scripts` folder of nnDetection to collect additional information of your environment. Since I didn't encounter the mentioned error, something inside the environment is probably the reason.

Best,
Michael

**Comment by YuqingCai0316** [comment]
I have the same problem,I have run python utils.py，and get
![2](https://user-images.githubusercontent.com/50909355/133217759-cc906316-f864-49cf-aad6-16686b75a945.png)

**Comment by mibaumgartner** [comment]
Hi @YuqingCai0316 ,

thanks for the feedback. The configuration looks good in general.
I'll try to reproduce the issue as soon as I can, due to an upcoming conference it will probably take some time though (sorry).

In the meantime, I would recommend using the docker installation if possible. 

Best,
Michael

**Comment by JoeNajm** [comment]
Hello @mibaumgartner @jk-blacker ,
I have the same issue, did you manage to find a solution for that problem?
Thanks in advance !
Joe

**Comment by mibaumgartner** [comment]
Dear @JoeNajm ,

this error never occurred to me, so it is quite hard to diagnose it right now. 

I think my candidates would be:
[All of them are somewhat unlikely but assuming your environment is correct I'm not sure what else could cause this]

- having a cuda capable device present during installation, there were errors on HPC clusters
- if CUDA_HOME is not None, it might point to the wrong version even though the nvcc commands reports a suitable CUDA version
- there might be a mismatch between the CUDA and GCC version (https://gist.github.com/ax3l/9489132) 
- maybe something related to the SM86 architecture which I didn't test yet

Best,
Michael
