### ISSUE TITLE
Evaluation on independent test set

### ISSUE THREAD

**Issue by dzeego** [MIC-DKFZ/nnDetection#225]
### :question: Question
Dear @mibaumgartner,

I am trying to evaluate the predictions of a pretrained model on an independent test set to which I  have the labels.
When launching nndet_eval with the --test argument I get an error that the .npz files of the labels are not found in preprocessed/labelsTs.
It seems to me that I have to preprocess the data in labelsTs.
So, how can I perform such an evaluation?

Many thanks in advance

**Comment by mibaumgartner** [comment]
Hi, the labels need to be placed in `raw_splitted/labelsTs` und you need to rerun the preprocessing -> it will skip most of the actual preprocessing and only convert the labels from the nifty images into actual bounding box coordinates (located in the npz files) which are used for the evaluation.
