### ISSUE TITLE
[Question] Installation question

### ISSUE THREAD

**Issue by rooskraaijveld** [MIC-DKFZ/nnDetection#226]
Hi!

I saw in previous questions/bugs that Pytorch CuDA and NVCC has to be the same, which is the case for me, however, I am still not able to run any step after nndet_example. What am I doing wrong?

This is my nndet_env:

----- PyTorch Information -----
PyTorch Version: 1.8.0+cu111
PyTorch Debug: False
PyTorch CUDA: 11.1
PyTorch Backend cudnn: 8005
PyTorch CUDA Arch List: ['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80', 'sm_86']
PyTorch Current Device Capability: (7, 5)
PyTorch CUDA available: True

----- System Information -----
System NVCC: nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0

System Arch List: 5.2 6.0 6.1 7.0 7.5 8.0 8.6+PTX
System OMP_NUM_THREADS: 1
System CUDA_HOME is None: True
System CPU Count: 40
Python Version: 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0]

----- nnDetection Information -----
det_num_threads 6
det_data is set True
det_models is set True

**Comment by mibaumgartner** [comment]
Dear @rooskraaijveld ,

thank you for your Issue, which error message do you receive?

Best,
Michael

**Comment by mibaumgartner** [comment]
Hmm, on first sight your env looks correct.

1) Try deleting the build folder and *.so file and re-install it 
2) Try setting the CUDA HOME path explicitly 

PS: always do (1) when running a new install, otherwise it won't recompile
