### ISSUE TITLE
Handling  duplicate nodules  after  detection.

### ISSUE THREAD

**Issue by Rajesh-ParaxialTech** [MIC-DKFZ/nnDetection#227]
Hello

How are duplicate nodules handled during nodule detection so that no nodule is reported more  than once, in nnDetection ?

Thanks
Rajesh D S

**Comment by mibaumgartner** [comment]
Hi,

theoretically NMS (via the defined threshold) should take care of this. Nevertheless, since it is a manual heuristic it won't remove all duplicates and some might remain. Also, other duplicates might be introduced with the ensembling step if the boxes are not sufficiently overlapping.
