### ISSUE TITLE
Run nnDetection on Cuda 12

### ISSUE THREAD

**Issue by kennyha85** [MIC-DKFZ/nnDetection#228]
### :question: Question
I'm trying  to run nnDetection on a GPU-server with RTX 4090 and Cuda 12. Can anybody tell me is there any way to run nnDetection on that CUDA version. I'm not sudoer of the GPU-server thus I can not install other cuda version.  Thanks!

**Comment by mibaumgartner** [comment]
Hi,

The cuda code should be compatible with CUDA12. The rest of the code will depend on the compatibility with PyTorch (note: only PyTorch 1.XX supported right now).

Best,
Michael
