### ISSUE TITLE
[Question]Training doesn't start or is stuck, stops at "using pin_memory on device 0"

### ISSUE THREAD

**Issue by ClimberXIE** [MIC-DKFZ/nnDetection#229]
Hi~
I met the same questions(#60)when I trained my model, then I turned to FAQ & Common Issues in README file and followed your steps there,the result was that the training without multiprocessing started correctly.How can I solve this problem? 
Looking forward to your reply.

my nndet_env :
----- PyTorch Information -----
PyTorch Version: 1.12.1
PyTorch Debug: False
PyTorch CUDA: 11.3
PyTorch Backend cudnn: 8302
PyTorch CUDA Arch List: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_37']
PyTorch Current Device Capability: (8, 6)
PyTorch CUDA available: True

----- System Information -----
System NVCC: nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0

System Arch List: None
System OMP_NUM_THREADS: 1
System CUDA_HOME is None: True
System CPU Count: 256
Python Version: 3.8.10 (default, Jun  4 2021, 15:09:15) 
[GCC 7.5.0]

----- nnDetection Information -----
det_num_threads 12
det_data is set True
det_models is set True

**Comment by mibaumgartner** [comment]
Hi, the env looks ok, can you check that the CPU is utilised when the dataloader starts? Usually it is a problem with `OMP_NUM_THREADS` or other external libraries which try to start several threads/processes (e.g. OpenCV).

**Comment by ClimberXIE** [comment]
> Hi, the env looks ok, can you check that the CPU is utilised when the dataloader starts? Usually it is a problem with `OMP_NUM_THREADS` or other external libraries which try to start several threads/processes (e.g. OpenCV).
Thanks for your reply, I will check that. And I also want to ask if I can use "nndet_train XXX -o augment_cfg.multiprocessing=False" for full training? I’ve seen "Don't use this for the full training, this is just one step of the debugging process"in the README file, but from the training log file, the training process seems to be fine, so why can't we use it for full training?

**Comment by ClimberXIE** [comment]
> Hi, the env looks ok, can you check that the CPU is utilised when the dataloader starts? Usually it is a problem with `OMP_NUM_THREADS` or other external libraries which try to start several threads/processes (e.g. OpenCV).

Thanks for your reply, I will check that. And I also want to ask why can't we use 'nndet_train XXX -o augment_cfg.multiprocessing=False' for full training（you mentioned that in the README file）? Since the training process seems to be okay from the training log file when I trained with "-o augment_cfg.multiprocessing=False".

**Comment by mibaumgartner** [comment]
The training pipeline looks something like this 

CPU process 1:    load batch -> augment batch  --- |
CPU process 2:   load batch -> augment batch  --- |
....                                                                                   | --- batch goes on GPU and network is trained 
CPU process X:  load batch -> augment batch  --- |

When you are only using multiprocessing=False, the GPU would idle most of the time since the CPU can not provide enough batches (it would only ru the main process, no other ones). This would yield veeeery long training times which are not acceptable for most people.

**Comment by ClimberXIE** [comment]
> The training pipeline looks something like this
> 
> CPU process 1: load batch -> augment batch ---> | CPU process 2: load batch -> augment batch ---> | ................................................................................. | --- batch goes on GPU and network is trained CPU process X: load batch -> augment batch ---> |
> 
> When you are only using multiprocessing=False, the GPU would idle most of the time since the CPU can not provide enough batches (it would only ru the main process, no other ones). This would yield veeeery long training times which are not acceptable for most people.

I got it, thanks for your explanation!
