### ISSUE TITLE
Preprocessing gets stuck with multiprocessing

### ISSUE THREAD

**Issue by dzeego** [MIC-DKFZ/nnDetection#236]
Hello,

When running the preprocessing using: `nndet_prep X -np 3`, at some point the preprocessing does not advance anymore and seems stuck. No error messages appear.
Any idea how to treat this issue?

Also is there a way to disable the cropping and the checking of the cropped data? 
At every time I relaunch the preprocessing after getting stuck, even though the cropping is not performed every time, the checking of the cases takes a lot time.

Thank you in advance.

**Comment by mibaumgartner** [comment]
Hey,

1) This sounds like you may run out of memory and the multiprocessing workers crash. Could you verify that this is not the problem? 
2) Yes, you can modify the preprocessing by overwriting values in the `prep` config, https://github.com/MIC-DKFZ/nnDetection/blob/main/nndet/conf/prep/process.yaml just add `-o crop=False` (there might be a change that the check will still run)

Best,
Michael

**Comment by dzeego** [comment]
Hello @mibaumgartner,

Thanks for the quick response!

    1. I am still investigating the first point
    2. That seems to be working thank you!

I would like to ask one more question if you don't mind:
How can I disable the low-resolution preprocessing (I don't need the TaskX/preprocessed/D3V001_3dlr1 folder) when I run `nndet_prep X`?

Best regards!
