### ISSUE TITLE
When is plan_inference.pkl generated?

### ISSUE THREAD

**Issue by dzeego** [MIC-DKFZ/nnDetection#238]
Hello @mibaumgartner,

After finishing the training (multiprocessing error at the last epoch persists) I am trying to run `nndet_predict` on my test set which is located in the raw_splitted folder in imagesTs.
However, when i launch `nndet_predict 0003 RetinaUNetV001_D3V001_3d --fold 0` I get:
FileNotFoundError: [Errno 2] No such file or directory: '/datadrive/nndetection_data/nndetection_models/Task0003_LesionDetection/RetinaUNetV001_D3V001_3d/fold0/plan_inference.pkl'

At what stage does the nndetection generate this file? and how can I mitigate this issue moving forward?

Also for some reason the `val_analysis`, `val_analysis_preprocessed`, `val_predictions`, `val_predictions_preprocessed`, `val_results`, and `val_results_preprocessed` folders were not generated. Is that normal?

Thank you in advance,
Best regards !

**Comment by mibaumgartner** [comment]
Dear @dzeego ,

did you run the training command with the `--sweep` option? - that should generate the plan and results 
`nndet_sweep` can be used to perform this manually -> it will predict the validaiton cases and derive the best set of postprocessing paramters for the validation set (those are the inference parameters which are saved into the plan_inference.pkl.
