### ISSUE TITLE
About adding LNDb  chest CT scan images for nodule detection training

### ISSUE THREAD

**Issue by Rajesh-ParaxialTech** [MIC-DKFZ/nnDetection#240]
Hello
I have planned to use LNDb chest CT scan datasets for training a nodule detector model using your nice "nnDetection".  Some of the images of these datasets do not have unit normal direction vectors.  Also the dimensions of these images are such that there are more than 512 voxels along the x-axis. Simply meaning, dataset image sizes are something like 674x512x442,  632x512x416, etc    where as usually the dataset images of "other than LNDb" datasets have typical size like 512x512x442,  512x512x416, etc, (i mean to say they will have same no of voxels along both x and y axes).  Now my questions are:
1. Can I use them for training ?
2. If i can, do i need to apply some transforms to these images and then use them for training ?

It would be very helpful, if i could get answers for these questions.  Thank you

Rajesh

**Comment by mibaumgartner** [comment]
Dear @Rajesh-ParaxialTech ,

nnDetection automatically handles images without unit normal direction vectors (note: the vectors this need to be orthogonal otherwise SimpleITK will complain) and of varying images sizes, nothing special todo. 

Best,
Michael
