### ISSUE TITLE
subprocess-exited-with-error when install nndetection

### ISSUE THREAD

**Issue by liuxia0725** [MIC-DKFZ/nnDetection#249]
Obtaining file:///D:/nnDetection
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\nnDetection\setup.py", line 7, in <module>
          from torch.utils.cpp_extension import BuildExtension, CppExtension, CUDAExtension, CUDA_HOME
        File "E:\anaconda3\envs\new_env\lib\site-packages\torch\utils\cpp_extension.py", line 25, in <module>
          from pkg_resources import packaging  # type: ignore[attr-defined]
      ImportError: cannot import name 'packaging' from 'pkg_resources' (E:\anaconda3\envs\new_env\lib\site-packages\pkg_resources\__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

how to solve this problem
pytorch: 1.13.0, python 3.10; cuda 1.17

**Comment by mibaumgartner** [comment]
Dear @liuxia0725 ,

I haven't encountered this Issue before, could you try to run it in a linux based docker container? nnDetection does not officially support Windows and based on your file paths, it looks like you might be using a windows based operating system.

**Comment by parataaito** [comment]
Hi there! 

Do you think that using WSL (Windows Subsystem for Linux) would work in that case?
