### ISSUE TITLE
I got this mistake when I install the nndetection   ERROR: Could not build wheels for nnunet, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by liuxia0725** [MIC-DKFZ/nnDetection#250]
here is the full log about the mistake: 
 creating build\bdist.win-amd64\wheel\nnunet\experiment_planning\alternative_experiment_planning\target_spacing
      copying build\lib\nnunet\experiment_planning\alternative_experiment_planning\target_spacing\experiment_planner_baseline_3DUNet_targetSpacingForAnisoAxis.py -> build\bdist.win-amd64\wheel\.\nnunet\experiment_planning\alternative_experiment_planning\target_spacing
      error: could not create 'build\bdist.win-amd64\wheel\.\nnunet\experiment_planning\alternative_experiment_planning\target_spacing\experiment_planner_baseline_3DUNet_targetSpacingForAnisoAxis.py': No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for nnunet
  Running setup.py clean for nnunet
Failed to build nnunet
ERROR: Could not build wheels for nnunet, which is required to install pyproject.toml-based projects

what can I do to fix this problem

**Comment by mibaumgartner** [comment]
Dear @liuxia0725 ,

can you post the versions of your environment. The nnU-Net version should be fixed and thus all files should be present.

Best,
Michael
