### ISSUE TITLE
Cannot find the task

### ISSUE THREAD

**Issue by liuxia0725** [MIC-DKFZ/nnDetection#259]
I have already build a folder named Task000 and follow the document create the raw_splitted folder and so on, But when I run  nndet_prep 000 It shows d:\nndetection\nndet\utils\check.py:52: UserWarning: Warning: 'det_num_threads' environment variable not set. Please read installation instructions again. Training will not work properly.
  warnings.warn(
'det_verbose' environment variable not set. Continue in verbose mode.
d:\nndetection\scripts\preprocess.py:381: UserWarning:
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  initialize_config_module(config_module="nndet.conf")
All tasks found: []
Searching for task_id: 000
Traceback (most recent call last):
  File "\\?\E:\anaconda3\envs\nndetection_env\Scripts\nndet_prep-script.py", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_prep')())
  File "d:\nndetection\nndet\utils\check.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "d:\nndetection\scripts\preprocess.py", line 386, in main
    cfg = compose(task, "config.yaml", overrides=_ov)
  File "d:\nndetection\nndet\utils\config.py", line 62, in compose
    task_name = get_task(task, name=True, models=models)
  File "d:\nndetection\nndet\io\paths.py", line 228, in get_task
    raise ValueError(f"Did not find task id {task_id}."
ValueError: Did not find task id 000.Options are: [] I have already set the environment 

Ps: I am running the model on windows I have already built the nndetection and run the test.

**Comment by mibaumgartner** [comment]
Dear @liuxia0725 ,

sorry for the late response. The folder needs to be named `Task000_[Some Name Here]` in order to be detected correctly.

Best,
Michael

**Comment by davidkflau** [comment]
Hi @liuxia0725 ,

do you mind sharing some insights to run nndetection on Windows?

Thanks!
