### ISSUE TITLE
[Question] Change post-processing parameters

### ISSUE THREAD

**Issue by NataliaAlves13** [MIC-DKFZ/nnDetection#265]
According to my sweep.log file the following parameters are used:

detections_per_img: 100 
score_thresh: 0 
topk_candidates: 10000 
remove_small_boxes: 0.01 
nms_thresh: 0.6

Is there a way to remove the remove_small_boxes threshold so that all 100 detections per image are included in the final predictions?

**Comment by partha-ghosh** [comment]
Hi @NataliaAlves13,
You can manually set a value for the `remove_small_boxes` threshold in the `plan_inference.pkl` file. This parameter can be found under the `inference_plan` key.

Best,
Partha
