### ISSUE TITLE
Question about pre-training a Task

### ISSUE THREAD

**Issue by NataliaAlves13** [MIC-DKFZ/nnDetection#267]
I have trained a model for a given task and now I want to pre-train the network with a large-scale data set to see if it improves performance. Is there an easy way to transfer all the pre-processing parameters from the original task to the pre-training task? The only difference is the detection classes. The original Task only has instances of one detection class (abdominal bleeding), while the pre-training task has instances of 21 different classes (organ landmarks). 
Any help here would be very welcome!

**Comment by mibaumgartner** [comment]
Dear @NataliaAlves13 ,

there is currently no pre-implemented way to transferring model weights between tasks but it shouldn't be too difficult to implement that logic. The exact complexity will differ depending on what you are planning to transfer, i.e. encoder weights, encoder + decoder weights or the entire architecture (probably requires exchanging the detection and regression layers at the end of the detection head). 

Best,
Michael
