### ISSUE TITLE
difference between  model_best-v1.ckpt, model_best-v2.ckpt and model_best.ckpt

### ISSUE THREAD

**Issue by Rajesh-ParaxialTech** [MIC-DKFZ/nnDetection#269]
Hello 

After training an nnDetection model for several epochs I could see (see figure below) the following trained models in the "det_models"  folder.  I could get what "model_best.ckpt" and "model_last.ckpt" are.  But  I  could not make out what model_best-v1.ckpt and model_best-v2.ckpt are. 

![image](https://github.com/user-attachments/assets/a125256d-6b96-4985-97c9-6af6e6bf494d)

Could anyone please explain ?

Rajesh

**Comment by mibaumgartner** [comment]
Dear @Rajesh-ParaxialTech ,

v1 and v2 are models which are usually created when continuing, restarting the training etc. They are generally the same as the normal _best mode.

Best,
Michael

**Comment by Rajesh-ParaxialTech** [comment]
Thanks a lot Michael
