### ISSUE TITLE
[Question] Inquiry about fold0 Directory Contents and Performance Metrics

### ISSUE THREAD

**Issue by ZHUJJFDU** [MIC-DKFZ/nnDetection#273]
### :question: Question

Hello,

I hope you're doing well. I've been going through your repository and I'm particularly interested in the fold0 directory. Could you please provide some insight into what each folder within fold0 is intended to store?

Additionally, after running the image prediction, I'm curious about where I can find the performance metrics. Are they logged somewhere in the output or is there a specific file I should be looking at?

I appreciate your help in clarifying these points.

**Comment by ZHUJJFDU** [comment]
![image](https://github.com/user-attachments/assets/a0c16b7a-2eb5-4bcf-812e-f56703f950dd)

**Comment by partha-ghosh** [comment]
Hi @ZHUJJFDU,
You can find the information about the folders here: https://github.com/MIC-DKFZ/nnDetection#results-1
And, the performance metrics are stored in the `val_results` folder.

Best,
Partha
