### ISSUE TITLE
training with just the preprocessed folder in det_models  folder crashes

### ISSUE THREAD

**Issue by DSRajesh** [MIC-DKFZ/nnDetection#278]
Recently I transferred the   'preprocessed'   folder (along with its unpacked preprocessed dataset, etc) alone into   "det_data/Task16_Luna/"    folder   and the 'plan.pkl' file  alone in and as "det_models/Task116_Luna/RetinaUNetV001_D3V001_3d/fold0/plan.pkl".    And all these folders were put in a SSD.    Then started training.   I made several attempts to run,  but the training crashed each  time leaving no error logs.  Could anyone please tell what may be happening ?

Rajesh

**Comment by DSRajesh** [comment]
The preprocessed folder size is 1.2  Tera Bytes .  I reduced det_num_threads=2  and tried. Even then it used to crash

**Comment by partha-ghosh** [comment]
Hi @DSRajesh,
To identify the problem we need more information, such as the output you got when you ran the training, the environment you used to run the commands, etc. Please check if you can run the training with the toy dataset in that environment. Also, please check that you transferred the `dataset.json` or `dataset.yaml` to the `Task16_Luna` along with the `preprocessed` folder.

Best,
Partha

**Comment by Rajesh-ParaxialTech** [comment]
Thanks Partha-Ghosh
I got the the following output while training
![image](https://github.com/user-attachments/assets/20c5ad10-ff93-4364-98a0-81f2bf780461).

dataset.json was present in the det_data/Task016_Luna  folder.   GPU/CUDA details are as follows.
![image](https://github.com/user-attachments/assets/08a279ab-2e6b-4163-b38e-27df211efc71)

![image](https://github.com/user-attachments/assets/71f08454-b3a6-4b51-a72e-fea5bf7cf2ef)

**Comment by DSRajesh** [comment]
Thanks Partha-Ghosh
Recently I transferred (as mentioned above) "preprocessed" folder etc, of a nnDetection object detection training model , which had stopped training midway, on a machine 'A'. The probable reason the training code quoted was "RAM becoming full".
![image](https://github.com/user-attachments/assets/7d7c054a-6075-4aec-aa6c-849736d452a3)



And I got the the following output while resuming the training on another machine 'B', using the command line "python scripts/train.py 116 -o train.mode=resume"
![image](https://github.com/user-attachments/assets/a1b21608-a005-4b38-9042-3e16f64fd4d1)
and then stopped abruptly without any error logs.

When i tried resuming the training using the command line "python scripts/train.py 116 --sweep -o train.mode=resume" , I got the following extra lines in the output when compared to the output shown above

![image](https://github.com/user-attachments/assets/97e45cce-c472-47fd-ae5b-f93337e28b9d)

In the above output we can see the training code was running inferences on all validation datasets one by one (we can see one of the many such inferences being run on validation dataset 127 out of the total of 131)

"dataset.json" was present in the det_data/Task016_Luna folder. GPU/CUDA details are as follows.


![image](https://github.com/user-attachments/assets/f4fb54c4-21fd-4202-8fe5-ddaac369b2cc)



![image](https://github.com/user-attachments/assets/cfd87ad9-2cc1-401f-9e89-7b962f7d2065)


I hope these details are sufficient. Was, changing the training location from machine 'A' to 'B' , the reason for this error ? Also why did the training stop in the first place, was it burdening the RAM ? The preprocessed folder was stationed in a SSD.

Thanks again
Rajesh

**Comment by DSRajesh** [comment]
Thanks Partha-Ghosh
Recently I transferred (as mentioned above) "preprocessed" folder etc, of a nnDetection object detection training model , which had stopped training midway, on a machine 'A'. The probable reason the training code quoted was "RAM becoming full", as shown below.
![image](https://github.com/user-attachments/assets/bb80b27c-4dd0-487f-be41-d4646c94dac2)

And I got the the following output while resuming the training on another machine 'B', using the command line "python scripts/train.py 116 -o train.mode=resume"

![image](https://github.com/user-attachments/assets/670778d0-1ed3-480b-8f41-94de736ca807)


and then stopped abruptly without any error logs.
When i tried resuming the training using the command line "python scripts/train.py 116 --sweep -o train.mode=resume" , I got the following extra lines in the output when compared to the output shown above

![image](https://github.com/user-attachments/assets/2fa7cd53-6542-4c3a-be12-985aa5914f78)


In the above output we can see the training code was running inferences on all validation datasets one by one (we can see one of the many such inferences being run on validation dataset 127 out of the total of 131)
"dataset.json" was present in the det_data/Task016_Luna folder. GPU/CUDA details are as follows.

![image](https://github.com/user-attachments/assets/ccec03a6-8bd9-4e73-b723-423276d5a22d)


![image](https://github.com/user-attachments/assets/9687c037-4f15-4b5b-9839-9dfc45fa8fff)


I hope these details are sufficient. Was, changing the training location from machine 'A' to 'B' , the reason for this error ? Also why did the training stop in the first place, was it burdening the RAM ? The preprocessed folder was stationed in a SSD.
Thanks again
Rajesh

**Comment by partha-ghosh** [comment]
Hi @DSRajesh,

It’s difficult to pinpoint the exact issue from the logs since the initial error suggests that the RAM being full may not be the root cause. Please monitor the RAM consumption to confirm whether it’s actually a memory-related issue.

The patch size might also be a factor. Since nnDetection adjusts patch size based on available GPU resources, you could try reducing it. For instance, setting `[80, 192, 160]` in the `plan.json` has worked well on our clusters.

It also looks like you’re resuming the training process at the validation phase, which might indicate that the training has already completed. Without the full log, it's hard to be sure. You could try manually loading the checkpoint to verify the current epoch.

If the issue persists, you might consider restarting the training from scratch on the preferred machine. Additionally, please share the complete log if the problem continues, and we’ll take another look.

Best,
Partha

**Comment by Rajesh-ParaxialTech** [comment]
Thanks a lot Partha
The issue was solved. As you had mentioned, the no of epochs of training i had fixed for the training  had elapsed and hence it was in the validation stage. I increased the no of epochs and resumed training. It works fine now.  Thanks a lot again
