### ISSUE TITLE
Problem with nndet_eval command

### ISSUE THREAD

**Issue by Pri0805** [MIC-DKFZ/nnDetection#281]
Hi, 

We had a question about the inference commands. 

When running nndet_eval we are getting the following error:

> FileNotFoundError: [Errno 2] No such file or directory: '/opt/data/Task106_lesiondetection/preprocessed/labelsTs/90010_0000000_boxes_gt.npz'

We ran the nnunet_predict command with the --no_preprocess flag to ensure the test data is preprocessed, but the labelsTs folder was still not created, yet the prediction command is running completely and we are getting predictions in the test_predictions folder. 

Could there be something missing with our folder structures / commands?

Thanks!

**Comment by partha-ghosh** [comment]
Hi @Pri0805,
One reason could be that there are no ground truth test labels in `labelsTs` folder in `raw_splitted`, which is why `labelsTs` folder is not created in the `preprocessed` directory. Please make sure your dataset comes with ground truth test labels.

Best,
Partha

**Comment by partha-ghosh** [comment]
If you check the `create_labels` function here:
https://github.com/MIC-DKFZ/nnDetection/blob/b0504dc6daa057d1a49d2e58203431117f1ff739/nndet/planning/experiment/utils.py#L58

It iterates over the `labelsTr` and `labelsTs` folders and does the preprocessing if they exist. Please run the `nndet_prep` command again. If it does not preprocess the `labelsTs` folder, then send us the entire log, we can take a look.

Best,
Partha
