### ISSUE TITLE
[Question] how to run all five folds?

### ISSUE THREAD

**Issue by ZheMin-1992** [MIC-DKFZ/nnDetection#31]
Hi, when I use the following command 
`nndet_train xxx --sweep`, where `xxx` denotes the task Id.
Only fold0 is generated in the model folder, how can I run other four folds?
Thank you for your help!

**Comment by mibaumgartner** [comment]
Hi @ZheMin-1992 ,

```
nndet_train XXX -o exp.fold=0 --sweep
nndet_train XXX -o exp.fold=1 --sweep
nndet_train XXX -o exp.fold=2 --sweep
nndet_train XXX -o exp.fold=3 --sweep
nndet_train XXX -o exp.fold=4 --sweep
```

You can use the above overwrite to change the fold.

Best,
Michael

**Comment by ZheMin-1992** [comment]
@mibaumgartner Thanks a lot for the answer!
