### ISSUE TITLE
[Question]Replicate result on paper

### ISSUE THREAD

**Issue by vankhoa21991** [MIC-DKFZ/nnDetection#37]
Hello,

I tried to replicate the results of nndetection on LUNA16 as in your paper, but I can not achieve the same performance marked in the paper (CPM=0.92). In fact what I obtain is CPM=0.84.
Did you use different set of parameter as presented in the paper? Or did you fine tuning the model?

Thanks,

**Comment by Derekabc** [comment]
@vankhoa21991 have you trained for 10-fold validation, in my understanding, it may take 2 days x 10 = 20 days to finish the training?

**Comment by vankhoa21991** [comment]
Indeed, almost 2 days on 1 GPU, if you have several GPUs you can make it faster

**Comment by BelieferQAQ** [comment]
> Hello,
> 
> I tried to replicate the results of nndetection on LUNA16 as in your paper, but I can not achieve the same performance marked in the paper (CPM=0.92). In fact what I obtain is CPM=0.84. Did you use different set of parameter as presented in the paper? Or did you fine tuning the model?
> 
> Thanks,



> 

Hello, what is the confidence threshold (probability threshold) of the selected candidate frame when calculating FROC and drawing FROC curve?

**Comment by mibaumgartner** [comment]
nnDetection does not save the corresponding confidence threshold since the FROCis solely defined on the basis of FP per image

**Comment by BelieferQAQ** [comment]
> 

You mean that all candidate frames predicted by the network are directly involved in the calculation of TP and FP (draw the FROC curve). Did not pass the first filtering of the confidence threshold
