### ISSUE TITLE
How to change the patch size

### ISSUE THREAD

**Issue by manonvanerp** [MIC-DKFZ/nnDetection#38]
### :question: Question

Hi, I've been trying nnDetection and so far the results are really nice. I would like to change the patch size though. I've found how to overwrite it in the yaml file but whenever I do this I keep getting the error:
`RuntimeError: The size of tensor a (19) must match the size of tensor b (20) at non-singleton dimension 4`
What are the constrains to changing the patch size? I tried several different number but can't seem to find a good fit.

**Comment by mibaumgartner** [comment]
Dear @manonvanerp,

happy to hear that the results look nice :) This error usually indicates that the patch size is not cleanly divisible by the stride of the network which will crash in the decoder pathway during upsampling.

There are several ways to check the strides of the network (all of them should give you the same result so simply chose one):
- Check `architecture/strides` inside `${det_models}/{your task}/RetinaUNetV001_D3V001_3d/plan_debug.json`
- Check `network.txt` inside `${det_models}/{your task}/RetinaUNetV001_D3V001_3d`
- Check `D3V001.pkl` inside `${det_data}/{your task}/preprocessed`

Compute the "total" stride of the network by multiplying the strides of each axis (e.g. 5 pooling layers each with stride 2 will result in a total stride of 2**5=32) and make sure that the patch size is divisible by it.

Best,
Michael

**Comment by manonvanerp** [comment]
Thanks for the response! I was able to get it working with this info. I was setting the patch size in the z direction too small (24). I've set it to 32 now and it's running :).
