### ISSUE TITLE
[Question] Should training take so long?

### ISSUE THREAD

**Issue by GabrielaProszczuk** [MIC-DKFZ/nnDetection#39]
### :question: Question
I prepared and preprocessed dataset Task010_Colon and there were no issues, but when I started training the net by 
`nndet_train 010 --sweep
`
it took extremely long time to finish Epoch 0 - almost 9 hours. I am using CUDA 11.2, GPU Nvidia Tesla K40 XL,  Pytorch 1.7.1+cu110 and working on an univeristy cluster which should allow my to train my net fast.
Is there anything I can do to make if faster? I'm not sure if it's my environment or is it my nnDetection configuration.

**Comment by mibaumgartner** [comment]
Dear @GabrielaProszczuk ,

9 hours for one epoch sounds quite slow indeed. Unfortunately, I don't have access to an equivalent GPU so I can not provide you with a reference time for your exact GPU type.

On an RTX 2080TI one epoch on Task 10 takes around 30minutes. Even considering that a K40 XL doesn't have tensor cores and has less performance than an RTX2080TI, 9 hours seems quite long (I would have expected something around ~2 hours).

You could look into https://github.com/MIC-DKFZ/nnDetection/issues/11 to find more info on potential bottlenecks. 

Notes: training on the K40XL will take a long time even with my estimated time.

**Comment by GabrielaProszczuk** [comment]
Thanks, I am checking for any bottleneck posibility but now I encountered memory error - is is possible that data created white training the first Epoch is exceeding 768 GiB? That is my limit and I get an error:
```
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full
bypassing sigterm
...
```
and file logs. I am working on university cluster and I'm not sure if its problem with my resources, but after this error the traning stops (its always around first few percent of Epoch 0).

**Comment by mibaumgartner** [comment]
Dear @GabrielaProszczuk,

the RAM consumption scales with the number of workers (set via `det_num_threads`) of the augmentation and the input size (i.e. batch size, patch size and number of modalities). While it is theoretically possible (by using a very very very large amount of workers) to reach such a large RAM consumption, "normal" values (somewhere between 6-32) should not result in such a RAM consumption.

Best,
Michael

**Comment by GabrielaProszczuk** [comment]
Hi, this error message was caused by my mistake of allocating too small memory in new task, so I'm glad it got resolved. Thank you for your answer.  But I have been thinking is it possible to save model after part of epochs if the training takes so long? I am still getting iteration time around 22.34s/it and  now 14 hours per epoch even after changing `det_num_threads` values to avoid bottlenecks.

**Comment by mibaumgartner** [comment]
Hi,
it is not possible to save the model in the middle of a training epoch, and changing the length of an epoch will affect the results because of Stochastic Weight Averaging (SWA) which snapshots the models at the end of the epoch (during the last 10 epochs).
The number of training batches per epoch and the number of epochs (which should be adjusted accordingly) can be changed in the config file (nndet/conf/train/v001.yaml). SWA can also be disabled in the config. Just note that those changes will change the final results...

Best,
Michael

**Comment by GabrielaProszczuk** [comment]
Okay, thank you for your answer. I have one more question - while it is not possible to predict on model with part of the epochs calculated I understand I can still resume training (option --resume from conf/config.yaml file)? On university cluster I have limit of  70h per task and if I cannot make if faster maybe I can still resume it after this time exceeds. I don't want to go too low on number of epochs and spoil final results by a lot.

**Comment by mibaumgartner** [comment]
Yes, resuming the training should work as it is handled by pytorch-lightning. I'm not 100% sure how well SWA interacts with resuming the training though (it should be handled by lightning but there might be some unwanted interactions since it is in beta and the learning rate scheduler is exchanged when SWA starts).

**Comment by hoangnhan1105** [comment]
> Thanks, I am checking for any bottleneck posibility but now I encountered memory error - is is possible that data created white training the first Epoch is exceeding 768 GiB? That is my limit and I get an error:
> 
> ```
>     raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
> RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full
> bypassing sigterm
> ...
> ```
> 
> and file logs. I am working on university cluster and I'm not sure if its problem with my resources, but after this error the traning stops (its always around first few percent of Epoch 0).

Hi @GabrielaProszczuk,
Can you tell me how exactly did you resolve this problem? I'm running nnDetection on Google Colab, and everything still runs normally until the training phase, when I met the same problem as you.
