### ISSUE TITLE
Hello, I am wondering whether nnDetection can be installed in Colab or without Docker?

### ISSUE THREAD

**Issue by Calvin-Pang** [MIC-DKFZ/nnDetection#4]
Hi, I am trying to install nnDetection and use it. And because my computer do not have a GPU, I am trying to install it by Google Colab. But from the README I got that I'd better use Docker to install it which is not supported in Colab. So  I am wondering whether there is some methods that I can install it without Docker?

**Comment by mibaumgartner** [comment]
Hi @Calvin-Pang ,

Docker is definitely the easiest solution. nnDetection needs to compile the CUDA code when it is installed and thus requires a correctly configured environment with CUDA (the installation procedure for local workstations is also given in the readme). Unfortunately, I don't know if that is possible in Colab, sorry. 

Best,
Michael

**Comment by Calvin-Pang** [comment]
OK thank you very much for reply. I will try it with some other methods.
