### ISSUE TITLE
[Bug] '_seg' not allowed in Task name/case path

### ISSUE THREAD

**Issue by manonvanerp** [MIC-DKFZ/nnDetection#40]
### :skull: Bug
For the past week, I've been trying to run a training but it continued to fail even though all other trainings I've done were completely fine. Preprocessing seemed fine but when running the nndet_train command, nnDetection couldn't find any files, but all my files where in the folders as expected like the other trainings I've done. 
I thought it was a problem on my side so I've investigated it and it turns out it's on your side. 

In file nnDetection/nndet/io/utils.py on line 50 you filter paths which have the substring '_seg' `case_paths = [f for f in case_paths if "_seg" not in f]`. 
Unfortunately, my task name was "Task504_segmwithmodalities", which has '_seg' in it. Hence, all the cases where removed from the list and no samples could be found in trying to create the train splits. 
Please consider not using the complete absolute path or at least warn in your readme about path names with '_seg' in them.

**Comment by mibaumgartner** [comment]
Dear @manonvanerp,

good catch! I'll fix it.

Best,
Michael

**Comment by mibaumgartner** [comment]
This should be fixed with the recent commits, so I'll close this Issue for now.
Please feel free to reopen this Issue if the problem persists or open a new one.
