### ISSUE TITLE
[Question] training slow on 8 V100 

### ISSUE THREAD

**Issue by hushunda** [MIC-DKFZ/nnDetection#41]
Multi-gpu is much slower than single gpu?

![选区_009](https://user-images.githubusercontent.com/21358656/143732131-88521413-1477-4468-adc7-259cc8ff9a1d.png)
>

**Comment by hushunda** [comment]
![选区_009](https://user-images.githubusercontent.com/21358656/143732232-b6d6657d-d55b-47e4-9dbb-fd3bb2c23021.png)

**Comment by mibaumgartner** [comment]
Hi @hushunda ,

FAQ from the Readme regarding multi GPU training:
```
Multi GPU training is not officially supported yet. Inference and metric computation are not properly designed to support these use cases!
```
Also: I didn't test Multi GPU thoroughly, so I can not guarantee good performance in that setting.

While the screenshots show that the GPUs are utilized, is the utilization constantly high? What is the training time for one epoch? Are all the other settings unchanged? 

Best,
Michael
