### ISSUE TITLE
[Question] Training few datasets at the same time

### ISSUE THREAD

**Issue by GabrielaProszczuk** [MIC-DKFZ/nnDetection#43]
Hello :)
Is it possible to execute multiple trainings at once? 
`nndet_train 007 --sweep`
`nndet_train 008 --sweep`
`nndet_train 010 --sweep`
I would execute them by individual scripts in batch mode and outputs would we saved in different files.

**Comment by mibaumgartner** [comment]
Dear @GabrielaProszczuk,

you can train in parallel on different GPUs. I don't recommend training multiple models on the same dataset.
