### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by vankhoa21991** [MIC-DKFZ/nnDetection#44]
Hello,

When I'm preprocessing the data, I run into an error:

File "/opt/nnDetection/nndet/preprocessing/preprocessor.py", line 259, in run_process
    data, seg, properties = self.apply_process(  File "/opt/nnDetection/nndet/preprocessing/preprocessor.py", line 304, in apply_process    data, seg, after = self.resample(
  File "/opt/nnDetection/nndet/preprocessing/preprocessor.py", line 379, in resample
    data, seg = resample_patient(data,
  File "/opt/nnDetection/nndet/preprocessing/resampling.py", line 53, in resample_patient
    return nn_preprocessing.resample_patient(data=data, seg=seg, original_spacing=original_spacing,
  File "/opt/conda/lib/python3.8/site-packages/nnunet/preprocessing/preprocessing.py", line 102, in resample_patient
    seg_reshaped = resample_data_or_seg(seg, new_shape, True, axis, order_seg, do_separate_z, cval=cval_seg,
  File "/opt/conda/lib/python3.8/site-packages/nnunet/preprocessing/preprocessing.py", line 193, in resample_data_or_seg
    reshaped.append(resize_fn(data[c], new_shape, order, cval=cval, **kwargs)[None])
TypeError: resize_segmentation() got an unexpected keyword argument 'cval'

This is related to the nnunet package?

**Comment by mibaumgartner** [comment]
Dear @vankhoa21991 ,

please pull the latest master. This should have been fixed quite some time back by fixing the nnU-Net versioning:
https://github.com/MIC-DKFZ/nnDetection/blob/9853d3e49e109dcd35b1ce70802c6e42aba879e1/requirements.txt#L2-L3

**Comment by vankhoa21991** [comment]
it's strange because I do have nnunet 1.6.6. I will try to get the latest version of nndet though.

**Comment by mibaumgartner** [comment]
Make sure to use the correct batchgenerators version as well :) (I think this is the problem)

**Comment by vankhoa21991** [comment]
You are right, somehow batchgenerators was upgraded to 0.23. It works when I downgrade to 0.21. 

Thanks for your help.

**Comment by koulakis** [comment]
Hello @mibaumgartner. We are trying to run `nndet_prep` and it seems that the upgrade of batchgenerators and nnunet 2 days ago made this bug re-appear. Additionally, in the latest version the downgraded versions are not accepted any more. Is there any workaround for that? (currently trying to downgrade nn-det)

**Comment by mibaumgartner** [comment]
Thanks for the report, I'll check it out

**Comment by mibaumgartner** [comment]
I reverted the nnU-Net and batchgenerators version to their old values which should fix the Issue (version will be bumped with the next nnDetection release).
