### ISSUE TITLE
[Question] How to acutally trigger lr model

### ISSUE THREAD

**Issue by bwittmann** [MIC-DKFZ/nnDetection#45]
### :question: Question

I have a question regarding the low res model. So `plan['trigger_lr1']` has been set to True. But this key is never used during training. So should I basically manually change `plan['data_identifier'] += 'lr1'` in train.py to force the use of lr model or is there a more intuitive way?

Thanks in advance!

**Comment by mibaumgartner** [comment]
Dear @bwittmann ,

can you check that the plan `D3V001_3dlr1` was created in the preprocessed data folder?
If it was generated, you need to manually trigger the training of the low res model by setting the correct plan when starting the training e.g. `nndet_train XXX -o plan=D3V001_3dlr1 --sweep`. 

If you have any idea on how the triggering of the low res could be communicated in a user-friendly way, please let me know. I'll add some additional info to the readme for this.

Best,
Michael

**Comment by bwittmann** [comment]
Hi @mibaumgartner 
Thanks for the fast reply! The plan is being generated. I guess I just missed that.

BR Bastian
