### ISSUE TITLE
[Question] Displaying results not working correctly

### ISSUE THREAD

**Issue by GabrielaProszczuk** [MIC-DKFZ/nnDetection#48]
Hello,
when using nndet_boxes2nii 
`
nndet_boxes2nii 010 RetinaUNetV001_D3V001_3d
`

I get directory with nii.gz and json files, but when displaying them all I get is all black nifiti file. Json files seems to be correct
Example:
`
{
    "1": {
        "score": 0.5186675190925598,
        "label": 0,
        "box": [
            16,
            199,
            24,
            245,
            269,
            322
        ]
    },
    "2": {
        "score": 0.9923214912414551,
        "label": 0,
        "box": [
            27,
            272,
            43,
            360,
            297,
            396
        ]
    }
}
`
Should files with results be displayed in different way than input nifti images?

**Comment by Derekabc** [comment]
Hi @GabrielaProszczuk, how do you solve the issue? I also faced black images
