### ISSUE TITLE
[Question] Steps to Train on LUNA16

### ISSUE THREAD

**Issue by Derekabc** [MIC-DKFZ/nnDetection#49]
Dear all, I want to train the nn_detection on the LUNA16 dataset following the instruction https://github.com/MIC-DKFZ/nnDetection and https://github.com/MIC-DKFZ/nnDetection/blob/main/projects/Task016_Luna/README.md.

To prepare the dataset, I run the command: python prepare.py and got the outputs as shown in below:
![image](https://user-images.githubusercontent.com/25771207/147842223-39f6bead-72ab-448c-8086-e1df29ee5f2d.png)
Inside the processed and raw_splitted folder:
![image](https://user-images.githubusercontent.com/25771207/147842228-99e2115e-0c82-4032-b14e-70b3b79b0cc8.png)
![image](https://user-images.githubusercontent.com/25771207/147842234-716c72c0-a1e0-4dd5-99fe-c4ea60bf6bbc.png)

And then I run the command nndet_unpack and run the command to train the model. The error like:
![image](https://user-images.githubusercontent.com/25771207/147842260-a014bde4-c41c-4be0-9077-29ee19e85b4d.png)

I changed the name of the pkl as 
![image](https://user-images.githubusercontent.com/25771207/147842272-a79b17dd-d631-4e2a-872e-066713eb1078.png)

Then I rerun the code, another issue occurs:
![image](https://user-images.githubusercontent.com/25771207/147842278-caa284be-d0e4-458b-b96a-9ec03bfc51be.png)

I am wondering what are the steps to train the model on LUNA16 and what I did wrong for the steps? Thank you so much!

Then I changed the path to the Imagedir and saw another error:
![image](https://user-images.githubusercontent.com/25771207/147888454-1e23a6a1-0bc2-433a-9782-58c9ad36b4d4.png)

I only saw the output file ending with "nii.gz".

**Comment by mibaumgartner** [comment]
Dear @Derekabc ,

sorry for the late response, I was on vacation. I think you forgot to run `nndet_prep` to preprocess the data. Make sure to rename the split files (especially the pickle one) to their original names, otherwise, the splits will be wrong.

Best,
Michael
