### ISSUE TITLE
Hello, I want to know whether nnDetection support Python3.7 and whether it can be trained with a png format dataset.

### ISSUE THREAD

**Issue by Calvin-Pang** [MIC-DKFZ/nnDetection#5]
Hello I have two questions about my using it.
1. In the code I found that nnDetection can only support Python>=3.8, but I want to use Colab which can only provide Python 3.7. To solve this question, I modify the config.py and change the ':=' operator to successfully install it. And then I successfully run the nndet_example code. But  I haven't try other commands, so I am wondering whether the process and train process can support Python 3.7 except the ':=' operator?
2. Another question is that whether I can use the png format dataset I found before to train with nnDetection? (The dataset consist of png images and csv file which include the coordinates)

**Comment by mibaumgartner** [comment]
Hi @Calvin-Pang ,

thank you for your question.

1. Yes, it should support python 3.7 except the ":=" operator.
2. One "trick" is to convert the png images to nifty ".nii.gz" images and use default values for the world coordinate system (spacing, rotation, origin). If the csv file contains bounding box coordinates, it is necessary to convert those to segmentations. It is probably a good idea to check that the converted boxes do not overlap (typically boxes can overlap while segmentations can not).


Also note: nnDetection only supports 3D (volumetric) data and does *not* support 2D ("normal" images) right now. This has several reasons:

(a) In our preliminary experiments we did not observe any benefit of using 2D networks for 3D data.

(b) Training 2D networks for 2D data requires a different set of optimal hyperparameters.

Best,
Michael

**Comment by Calvin-Pang** [comment]
Thank you very much for your answer!
