### ISSUE TITLE
[Question]Abaout Installation

### ISSUE THREAD

**Issue by Erinzhu** [MIC-DKFZ/nnDetection#59]
### :question: Question

Hello，
When I tested the installation, the following error occurred, which step was not done?
Thank you very much！
![s](https://user-images.githubusercontent.com/87703403/159228972-5cd12d5a-5a58-43d2-8893-647499b38085.png)

**Comment by mibaumgartner** [comment]
I'll close the issue for now, please feel free to reopen if anything else comes up.
