### ISSUE TITLE
[Question] Training with a specific fold?

### ISSUE THREAD

**Issue by RoqueRouteiral** [MIC-DKFZ/nnDetection#61]
### :question: Question

Is it possible to run the nnDetection with a specific train/val split? I see that the specific fold is one of the possible arguments that can be given as argument when training, but I am not sure where to specify which cases/patients belong to the desire fold.

In the nnUNet framework, that was possible by defining this in the splits_final.pkl. Is there an equivalent? or an easy workaround?

Thank you in advance.

Best,

Roque

**Comment by mibaumgartner** [comment]
I'll close the issue for now, please feel free to reopen if anything else comes up.
