### ISSUE TITLE
nnDetection model

### ISSUE THREAD

**Issue by rooskraaijveld** [MIC-DKFZ/nnDetection#63]
Hi, 

I was wondering if there was a way to load nnDetection model architecture in Python? I see loading the checkpoints works using torch, but getting the final nnDetection model is not yet clear to me. Is there a way that I could do this? :)

Eg:
loaded_model = nnDetection()
loaded_model.load_state_dict(torch.load('model_best.ckpt'))

Thanks!

**Comment by mibaumgartner** [comment]
Dear @rooskraaijveld ,

yes, I linked the lines you are looking for are here: https://github.com/MIC-DKFZ/nnDetection/blob/509a06ed7611df97609a9427b973cc97c9153b32/nndet/inference/loading.py#L91-L100

The plan and config can be found in the training folder where the checkpoints are located as well. 

Best,
Michael

**Comment by rooskraaijveld** [comment]
Thanks Michael! That really helps :) 

I am trying to run the loading.py file in Spyder for further experiments. 
-----
import sys
#sys.path.append('W:\_Roos\nnDetection-main')

import os
from functools import partial
from pathlib import Path
from typing import Sequence, Optional

import torch
from loguru import logger


from nndet.io.paths import Pathlike
from nndet.ptmodule import MODULE_REGISTRY

def load_final_model(
    source_models: Path,
    cfg: dict,
    plan: dict,
    num_models: int = 1,
    identifier: str = "last",
    ) -> Sequence[dict]:
    """
    Load final model from training

    Args:
        source_models: path to directory where models are saved
        cfg: config used for experiment
            `model`: name of model in DETECTION_REGISTRY
        plan: plan used for training
        num_models: Only supports one model
        identifier: looks for identifier inside of model name

    Returns:
        Sequence[dict]: loaded models
            `model`: loaded model
            `rank`: rank is always 0
    """
    assert num_models == 1, f"load_final_model only supports num_models=1, found {num_models}"
    logger.info(f"Loading {identifier} model")

    model_names = list(source_models.glob('*.ckpt'))
    model_names = [m for m in model_names if identifier in str(m.stem)]
    assert len(model_names) == 1, f"Found wrong number of models, {model_names} in {source_models} with {identifier}"

    path = model_names[0]
    model = MODULE_REGISTRY[cfg["module"]](
        model_cfg=cfg["model_cfg"],
        trainer_cfg=cfg["trainer_cfg"],
        plan=plan,
        )
    state_dict = torch.load(path, map_location="cpu")["state_dict"]
    t = model.load_state_dict(state_dict)
    logger.info(f"Loaded {path} with {t}")
    model.float()
    model.eval()
    return [{"model": model, "rank": 0}]
----
However, I keep getting the following error and I am unsure what nndet._C is. Could you help out?

  File "W:\_Roos\nnDetection-main\nndet\core\boxes\nms.py", line 22, in <module>
    from nndet._C import nms as nms_gpu

ModuleNotFoundError: No module named 'nndet._C'

Best,
Roos

**Comment by mibaumgartner** [comment]
Dear @rooskraaijveld ,

`nndet._C` is the extension which contains the compiled cuda kernel (i.e. NMS), if the import does not work, something went wrong during the installation. Please check the readme and FAQ section for common questions and on how to approach this.

Best,
Michael

**Comment by mibaumgartner** [comment]
Since the new Issue seems to be related to the installation and not the original question, I'll close the Issue for now but please feel free to reopen or open  a new one if anything else comes up.
