### ISSUE TITLE
Error on building the Docker image. [Bug]

### ISSUE THREAD

**Issue by KnowYourNME1** [MIC-DKFZ/nnDetection#64]
### :skull: Bug

When building the Docker as described in the guidelines:
`docker build -t nndetection:0.1 --build-arg env_det_num_threads=6 --build-arg env_det_verbose=1 .`

Then an error is raised during the installation of the requirements.

```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

nevergrad 0.5.0 requires numpy>=1.21.1, but you'll have numpy 1.19.2 which is incompatible.
```
This is caused by the update of nevergrad to 0.5 which requires an higher version (>=1.21.1) of numpy.

The error does not result on the interruption of the build but it results in runtime errors when try to run nnDetection code using the Docker.

### Possible Solution
A simple solution is to set the version of nevergrad to 0.4 in the requirements. This prevents the error because 0.4 does not require a numpy update.  
This should not cause unexpected behavior running nnDetection later on. However the best solution is to set nevergrad version as the one used to develop nnDetection.

### Environment
Running on an Ubuntu server with NVIDIA docker installed.

**Comment by mibaumgartner** [comment]
Dear @KnowYourNME1 ,

thank you for your bug report, I limited the nevergrad version to `<0.5.0` for now and will look into bumping the versions in general at a later point in time. If there are any other version mismatches coming up, please don't hesitate to add them here as well. 

Best,
Michael

**Comment by mibaumgartner** [comment]
Update: reduced nevergrad to <=0.4.2 and tested the new docker buld locally. Since this should now work again, I'll close the Issue for now, but please reopen it if the error persists.
