### ISSUE TITLE
[Question]LightningDeprecationWarning

### ISSUE THREAD

**Issue by tejavu** [MIC-DKFZ/nnDetection#71]
While running the Toy dataset example, the training stops after 59 Epochs and shows this:
![image](https://user-images.githubusercontent.com/100778166/165325990-d5e57c3c-7828-497c-970e-83865fdf8bc1.png)

this is details of my environment (using nndet_env) 

![image](https://user-images.githubusercontent.com/100778166/165326330-4a16c54a-5fbe-4714-beb7-7e65458c00d4.png)

I have installed everything else as per the requirements.txt. Could you please clarify why this error might occur?

**Comment by mibaumgartner** [comment]
Dear @tejavu ,

could you clarify which error you mean? The screenshot, shows a Deprecation-Warning for future versions of PytorchLightning but it is not an Error and does not stop the script.

Best,
Michael

**Comment by tejavu** [comment]
> Dear @tejavu ,
> 
> could you clarify which error you mean? The screenshot, shows a Deprecation-Warning for future versions of PytorchLightning but it is not an Error and does not stop the script.
> 
> Best, Michael

I wanted to know why the training does not continue until 100 Epochs, or is the example set to run for 59 Epochs ?

**Comment by mibaumgartner** [comment]
It will always train for 60 epochs (starting at 0), so everything is fine :)  Since the Toydataset is really easy and super small you can train much fewer epochs there but some datasets require quite a long schedule due to their size -> this is why the default is set to quite an extensive schedule.

**Comment by tejavu** [comment]
> It will always train for 60 epochs (starting at 0), so everything is fine :) Since the Toydataset is really easy and super small you can train much fewer epochs there but some datasets require quite a long schedule due to their size -> this is why the default is set to quite an extensive schedule.

Thank you so much for your response!
