### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'saved/Task010_Colon/RetinaUNetV001_D3V001_3d/fold0/plan.pkl'

### ISSUE THREAD

**Issue by Kyfafyd** [MIC-DKFZ/nnDetection#78]
### :question: Question

I have strictly follow the instructions and get the error, could you please help me solve it?
```
FileNotFoundError: [Errno 2] No such file or directory: 'saved/Task010_Colon/RetinaUNetV001_D3V001_3d/fold0/plan.pkl'
```

**Comment by mibaumgartner** [comment]
Dear @Kyfafyd ,

Could you provide some more info, e.g.
Which command/step are you trying to run? Which command(s) did you run previously?

Best,
Michael

**Comment by Kyfafyd** [comment]
I am running `nndet_train Task010_Colon --sweep`
Previously, I have run:
```shell
nndet_prep Task010_Colon
nndet_unpack ${det_data}/Task010_Colon/preprocessed/D3V001_3d/imagesTr 6
```

**Comment by mibaumgartner** [comment]
Thanks for the update, two things here:
1) I guess the program crashes pretty much at the beginning? (probably here https://github.com/MIC-DKFZ/nnDetection/blob/9aaa3f43949fca0e7b699cdbbc63b8e2f9afef45/scripts/train.py#L256) Can you check that the path which is printed exists? Please also check the env variable `det_models` and make sure that is exists and points to the right location. 
2) If the above does not help, could you please provide the full error message with the tracelog so I can identify the exact line where it fails.

Best,
Michael

**Comment by mibaumgartner** [comment]
The error is a bit misleading here, while it states a missing file the error is actually related to a wrong location of the folder (the operation is not a read operation but a write operation). 

Can you set nndet_models to an absolute path please, i.e. it should start with something like '/home/...' or similar. One way to figure it out: navigate to the models directory you want to use and enter 'pwd' in the terminal (inside that folder.

**Comment by Kyfafyd** [comment]
Thanks very much, absolute path works!
Besides, I have another question, if I only have detection bounding boxes as labels, how can I use nnDetection?
I am considering the following pipeline, I would appreciate it very much if you could check it is right or not:
- given a bbox B (category: 1), fill in the B as `1` to produce its segmentation mask (others `0`)
- nn_pre -> nn_unpack -> nn_train...

Another question is how to increase the threshold of evaluating mAP? e.g. from 0.1 to 0.25/0.50

**Comment by mibaumgartner** [comment]
1) Training with pure bounding boxes is not directly possible with nnDetection right now. One way to get around the limitation is to convert the box into a segmentation (as you have already stated). Each object need a different "instance" number in the segmentation and the class of each object is defined in the corresponding json file. (https://github.com/MIC-DKFZ/nnDetection#label-format) 
Note that while boxes can overlap (even though unlikely in 3D) sergmentations can not which is a current limitation of this workaround.

2) The "opnline" mAP computed during training is instantiated here https://github.com/MIC-DKFZ/nnDetection/blob/9aaa3f43949fca0e7b699cdbbc63b8e2f9afef45/nndet/ptmodule/retinaunet/base.py#L110-L114 . You could adjust the IoU values inside that class. (Note: the results produced at the end of the training include IoU 0.1, 0.2, 0.3, ... but are not displayed during training to reduce clutter in the logs)

**Comment by mibaumgartner** [comment]
Since there was no update for some time,  I'll close the Issue for now but if anything else comes up please reopen (if the same) or open a new one.
