### ISSUE TITLE
How to train with predefined train and val split

### ISSUE THREAD

**Issue by Kyfafyd** [MIC-DKFZ/nnDetection#79]
### :question: Question

Current model is doing k-fold cross-validation.
So if I have predefined train and val split, how to do the whole process?

**Comment by mibaumgartner** [comment]
Does this Issue answer your question? https://github.com/MIC-DKFZ/nnDetection/issues/61
(No other changes than the manually created splits file are required)

**Comment by mibaumgartner** [comment]
Since there was no update for some time,  I'll close the Issue for now but if anything else comes up please reopen (if the same) or open a new one.
