### ISSUE TITLE
env error

### ISSUE THREAD

**Issue by zzu0654** [MIC-DKFZ/nnDetection#80]
### :question: Question

 Recently, I tried to test nnDetection with the command :python -c "import torch; import nndet._C; import nndet" . , but I got a problem:
ERROR: 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /home/data8/zhengcy/Projects/nnDetection/nndet/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Z8nms_cudaRKN2at6TensorES2_f

Thank you for your help!

nnDetection was installed from [ source].
----- PyTorch Information -----
PyTorch Version: 1.11.0
PyTorch Debug: False
PyTorch CUDA: 11.3
PyTorch Backend cudnn: 8200
PyTorch CUDA Arch List: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_37']
PyTorch Current Device Capability: (8, 6)
PyTorch CUDA available: True

----- System Information -----
/bin/sh: 1: nvcc: not found
System NVCC:
System Arch List: None
System OMP_NUM_THREADS: 1
System CUDA_HOME is None: True
System CPU Count: 36
Python Version: 3.8.0 (default, Nov  6 2019, 21:49:08)
[GCC 7.3.0]

----- nnDetection Information -----
det_num_threads 6
det_data is set True
det_models is set True

**Comment by mibaumgartner** [comment]
Dear @zzu0654 ,

it looks like your CUDA installation is not working correctly (as indicated by the failed `nvcc` error). Please also check the FAQ Section (https://github.com/MIC-DKFZ/nnDetection#faq--common-issues) - `Installation & Initial Setup Errors` for how an example output should look like.

Best,
Michael

**Comment by zzu0654** [comment]
Thanks for your help, I have solved the environment problem

**Comment by mibaumgartner** [comment]
Thanks for the update, I'll close the issue for now but if anything else comes up please reopen / or open a new one.
