### ISSUE TITLE
[Question] Changing number of iterations per epoch 

### ISSUE THREAD

**Issue by tejavu** [MIC-DKFZ/nnDetection#81]
Is there a possibility of changing the number of iterations per epoch and if so, where can this be changed?

**Comment by mibaumgartner** [comment]
Dear @tejavu ,

the number of iterations can be changes in the config https://github.com/MIC-DKFZ/nnDetection/blob/9aaa3f43949fca0e7b699cdbbc63b8e2f9afef45/nndet/conf/train/v001.yaml#L45 or by providing the overwrite `-o trainer_cfg . num_train_batches_per_epoch =XXX`

Best,
Michael

**Comment by tejavu** [comment]
Thank you so much. I am new to this and I tried editing the yaml file using Vscode and saving it, but the changes do not reflect while training. And could you explain how to use the `-o trainer_cfg . num_train_batches_per_epoch =XXX` command, should it be written after `nndet_train [Task]` or somewhere else ?

**Comment by tejavu** [comment]
Thank you, it works
