### ISSUE TITLE
[install error about nvcc]

### ISSUE THREAD

**Issue by sunpengmri** [MIC-DKFZ/nnDetection#82]
### :question: Question
<! i am trying to install nnDet in a ubuntu 20.04 system, but get a strange error message-->

My nvcc path seems right, 
which nvcc
/usr/local/cuda/bin/nvcc

ERROR: Command errored out with exit status 1:
     command: /home/peng/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/peng/github/01_AI/04_MIC-DKFZ/nnDetection/setup.py'"'"'; __file__='"'"'/home/peng/github/01_AI/04_MIC-DKFZ/nnDetection/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/peng/github/01_AI/04_MIC-DKFZ/nnDetection/
    Complete output (24 lines):
    /home/peng/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py:487: UserWarning: Normalizing 'v0.1' to '0.1'
      warnings.warn(tmpl.format(**locals()))
    Build csrc
    Building with sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)
    main_file [PosixPath('/home/peng/github/01_AI/04_MIC-DKFZ/nnDetection/nndet/csrc/ops.cpp')]
    source_cpu []
    source_cuda [PosixPath('/home/peng/github/01_AI/04_MIC-DKFZ/nnDetection/nndet/csrc/cuda/nms.cu')]
    Adding CUDA csrc to build
    CUDA ARCH None
    running develop
    running egg_info
    writing nndet.egg-info/PKG-INFO
    writing dependency_links to nndet.egg-info/dependency_links.txt
    writing entry points to nndet.egg-info/entry_points.txt
    writing requirements to nndet.egg-info/requires.txt
    writing top-level names to nndet.egg-info/top_level.txt
    reading manifest file 'nndet.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    adding license file 'LICENSE'
    writing manifest file 'nndet.egg-info/SOURCES.txt'
    running build_ext
    error: [Errno 2] No such file or directory: '/usr/local/cuda/bin/bin/nvcc'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/peng/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/peng/github/01_AI/04_MIC-DKFZ/nnDetection/setup.py'"'"'; __file__='"'"'/home/peng/github/01_AI/04_MIC-DKFZ/nnDetection/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

My system information:
----- PyTorch Information -----
PyTorch Version: 1.11.0
PyTorch Debug: False
PyTorch CUDA: 11.3
PyTorch Backend cudnn: 8200
PyTorch CUDA Arch List: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_37']
PyTorch Current Device Capability: (7, 5)
PyTorch CUDA available: True

----- System Information -----
System NVCC: nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Wed_Jun__2_19:15:15_PDT_2021
Cuda compilation tools, release 11.4, V11.4.48
Build cuda_11.4.r11.4/compiler.30033411_0

System Arch List: None
System OMP_NUM_THREADS: None
System CUDA_HOME is None: False
System CPU Count: 16
Python Version: 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]

----- nnDetection Information -----
det_num_threads None
det_data is set False
det_models is set False

**Comment by mibaumgartner** [comment]
Dear @sunpengmri ,

this seems to be a tricky one since the nvcc in the environment works fine. Are there any external factors (like activating a new env before installation) or something which might cause the wrong path during installation?

The installation is looking into `.../bin/bin/nvcc` while it is in `../bin/nvcc`(the latter one being correct and also found on my system).

Could you try setting `export CUDA_HOME=/usr/local/cuda` just to be safe? 

Best,
Michael

**Comment by sunpengmri** [comment]
@mibaumgartner 
Thanks a lot, Michael. Indeed there is a wrong setup of CUDA_HOME. After export CUDA_HOME=/usr/local/cuda, I have installed nnDet successfully.

Best
Peng
