### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by tohsakask** [MIC-DKFZ/nnDetection#83]
### :question: Question

The training time of LUNA16 is 3 hours per epoch. And I have saved the preprocessed data directory on SSD.
I found the time of these code have last almost 1s for each cases.
### 
            data_batch[batch_idx] = save_get_crop(case_data,
                                                  crop=crop,
                                                  mode=self.pad_mode,
                                                  **self.pad_kwargs_data,
                                                  )[0]
            seg_batch[batch_idx] = save_get_crop(case_seg,
                                                 crop=crop,
                                                 mode='constant',
                                                 constant_values=-1,
                                                 )[0]

Is it common?

**Comment by mibaumgartner** [comment]
Since there was no update for some time I’ll close this Issue for now.
Please feel free to reopen this Issue if the problem persists or open a new one.
