### ISSUE TITLE
[Question] Test Installation ImportError : undefined symbol: _Z8nms_cudaRKN2at6TensorES2_f

### ISSUE THREAD

**Issue by maxencewynen** [MIC-DKFZ/nnDetection#85]
### :question: Question

Hi! 

First of all, thanks a lot for this incredibly well documented repo.

I have an error occurring while testing if nndet has been installed well (`python -c "import torch; import nndet._C; import nndet"
`). The error is similar to the issues #20 , #58 and #80 and stipulates:

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /home/ma2257/nnDetection/nndet/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Z8nms_cudaRKN2at6TensorES2_f`

I am trying to install nnDetection on a hpc cluster, mainly trying to use it with an RTX2080. This GPU runs with CUDA 11.1 and I do not have the permission to upgrade the CUDA version. By reading other issues and following advices that were posted to answer them, I've come up with a bash scipt to install it from scratch in a new conda environment, here it is:

```bash
rm -rf /home/ma2257/nnDetection/build
conda create -n $1 python=3.8.8 -y
conda activate $1
conda install -c nvidia cuda-nvcc
conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge -y
conda install -c anaconda cmake -y
git config --global url."https://".insteadOf git:// -y
conda deactivate
conda activate $1
loadspack
spack load gcc@9.3.0
rm -rf /home/ma2257/nnDetection/build
pip install -e /home/ma2257/nnDetection/
echo "Done."
```

After the installation is done (during no error occurs), this is the output I get from `nndet_env`:

```
----- PyTorch Information -----
PyTorch Version: 1.8.0
PyTorch Debug: False
PyTorch CUDA: 11.1
PyTorch Backend cudnn: 8005
PyTorch CUDA Arch List: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_37']
PyTorch Current Device Capability: (7, 0)
PyTorch CUDA available: True


----- System Information -----
System NVCC: nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

System Arch List: None
System OMP_NUM_THREADS: 1
System CUDA_HOME is None: True
System CPU Count: 40
Python Version: 3.8.8 (default, Apr 13 2021, 19:58:26)
[GCC 7.3.0]


----- nnDetection Information -----
det_num_threads 6
det_data is set True
det_models is set True
```

The fixes suggested for solving this bug I've tried:

- Checking if my GPU driver is installed with `nvidia-smi`: shows a CUDA version of 11.1
- Checking if CUDA is available after activating the environment: OK
- Check if CUDA is installed correctly with `nvcc --version`: OK, shows a a build cuda_ version of 11.7; V11.7.64
- Checking if the PyTorch CUDA and NVCC CUDA versions match: For this, I have tried the following combinations: (PyTorch: 11.1; -- NVCC: 11.7.64 ; PyTorch: 11.1 -- NVCC: 11.3.0 ) and none of them fix the error mentioned earlier. I strongly suppose that the error lies here somewhere but I really can't figure out what exactly is going wrong.
- Removing the build folder before and after each install

Unfortunately, none of these suggestions get me rid of the ImportError...

Is there something I am missing or that I could do?

Thanks for your help!

**Comment by mibaumgartner** [comment]
Dear @maxencewynen ,

thank you for your detailed report.

1) Not related to your problem but probably still a good thing to know: Having a minor cuda mismatch is usually okay (there are no official guarantee that it will work though), so I would look into installing pytorch 1.9 or 1.10. There were some issues with older pytorch versions where 3D Mixed Precision didn't provide a training speed up and thus leeds to long training times. The original workaround was to compile pytorch from source to gain that benefit. Newer version (I **think** 1.9 onwards) included that benefit from the pip installable version (I never tried the conda one, so maybe it is different there).

2) If CUDA is preinstalled on your cluster, there shouldn't be a need to install it from conda. I never tried the conda installed CUDA version, so it is quite difficult for me to give you an informed guess what is going wrong. It may be as simple as pointing `CUDA_HOME` to the correct installation though (e.g. as here https://github.com/MIC-DKFZ/nnDetection/issues/82). The env output looks correct in general though. 

As you correctly stated it is most likely related to a major mismatch in the CUDA versions. One other cause is the reinstallation/upgrading of PyTorch which requires an new installation of nnDet as well (usually these are solvable by deleting the build folder and rerunning the pip install command). 
I guess the last resort would be to look into the docker build of nnDet which takes care of those dependencies.

Best,
Michael

**Comment by maxencewynen** [comment]
Thanks for you quick answer!

After a long search, I finally fixed the error. Turns out I had to run the installation on the GPU node of the cluster (`#SBATCH --gres=gpu:rtx2080:1`) and -like you suggested- set `CUDA_HOME `to the correct path (in my case `/usr/local/cuda-11.2`) .

Thanks again for your help!
