### ISSUE TITLE
[Question] How to adjust the window center and window level for my own dataset? 

### ISSUE THREAD

**Issue by tohsakask** [MIC-DKFZ/nnDetection#87]
### :question: Question
Hello, I am new for nnDetection and Medical Images.
I found the CTs have different window center and window level. How to adjust the window center and window level for a specific disease?

**Comment by mibaumgartner** [comment]
Dear @tohsakask ,

nnDetection does not rely on window center and window levels. Windowing is great to visualise scans for humans but it does not create "new information" for a machine, so it is somewhat open if it is really needed when training a neural network.
Nevertheless, you can still apply a windowing to the CT scans manually before feeding them into nnDetection. The intensity normalisation (on top of those scans) is than performed according to the modalities stated in the `dataset.json`. Please refer to the nnU-Net Paper to find out more information about the normalisation schemes of CT and other modalities.

Best,
Michael

**Comment by tohsakask** [comment]
> ### ❓ Question
> Hello, I am new for nnDetection and Medical Images. I found the CTs have different window center and window level. How to adjust the window center and window level for a specific disease?



> Dear @tohsakask ,
> 
> nnDetection does not rely on window center and window levels. Windowing is great to visualise scans for humans but it does not create "new information" for a machine, so it is somewhat open if it is really needed when training a neural network. Nevertheless, you can still apply a windowing to the CT scans manually before feeding them into nnDetection. The intensity normalisation (on top of those scans) is than performed according to the modalities stated in the `dataset.json`. Please refer to the nnU-Net Paper to find out more information about the normalisation schemes of CT and other modalities.
> 
> Best, Michael

Thank you very much for your help!

**Comment by mibaumgartner** [comment]
I'll close this for now but if anything else comes up please feel free to open a new Issue.
