### ISSUE TITLE
[Question] Needing nnDetection and nnUNet with custom trainer

### ISSUE THREAD

**Issue by demcbs** [MIC-DKFZ/nnDetection#93]
Hi, I have 2 different tasks I need to work on with my data, one pure segmentation, one data oriented.

I have used nnUNet for the segmentation task, but with a slightly modified trainer. Since then I've installed nnDetection for the second task. That seems to have reinstalled nnUNet as a normal package, which then of course does not have the modified trainer, such that my models no longer run from the command line.

Have you perhaps got any advice on how to proceed, such that I can use both nnUNet with a custom trainer and nnDetection?

**Comment by mibaumgartner** [comment]
Dear @demcbs ,

 the preferred way of tackling your issue would be to create different virtual environments to decouple the requirements of the two projects.

Best
Michael

**Comment by demcbs** [comment]
Hi Michael,

Thanks for your response, it took a bit but it works :+1: I did run into one issue along the way that might be relevant to you (or others), so just in case it is:

When making a new environment from scratch, and following the normal nnDetection installation instructions, on the moment of pip install -e . in the nnDetection folder,  a legacy install failure for SimpleITK occurred.

What resolved it for me is specifying python=3.9.7 (as opposed to the automatically installed 3.10.something when the version was left unspecified) on the environment creation.

**Comment by mibaumgartner** [comment]
@demcbs thanks for the update, that is nice to know. I would consider this a SimpleITK problem rather than a nnDetection problem though.

**Comment by demcbs** [comment]
Yeah, that makes sense :+1:
