### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by midya2020** [MIC-DKFZ/nnDetection#96]
I used nnUnet code and recently started working with NNDetection. However, I have a little difficulty in installing this and really appreciate your help in solving the issue. I am using HPC and we already have CUDA=10.2 and cudnn. I am using CUDA 10.2, cudnn/8.02-cuda10.2, pytorch 1.12.
I followed the following steps:
1. Created a separate conda environment <NNDetection>
2. Clone nnDetection with git clone https://github.com/MIC-DKFZ/nnDetection
3. cd nnDetetion
4. pip install -e .

while running pip install "-e ." getting this error --"error: command '/usr/bin/gcc' failed with exit code 1"
However, I am not getting the reason behind this. Kindly suggest.

**Comment by mibaumgartner** [comment]
Dear @midya2020 ,

can you check that your env is correctly setup (see the FAQ section of the readme for more info)? The error message without trace is rather uninformative, but maybe there is a compatibility Issue between the installed CUDA und gcc version. If would be helpful to see the entire error message.

Best,
Michael

**Comment by mibaumgartner** [comment]
Since there was no update for some time I’ll close this Issue for now.
Please feel free to reopen this Issue if the problem persists or open a new one.
