### ISSUE TITLE
[Question] Compute metrics file

### ISSUE THREAD

**Issue by JoeNajm** [MIC-DKFZ/nnDetection#98]
### :question: Question
Hello,
I was wondering in which file is the metrics computation done (AP, AR and mAP). Indeed, I'm trying to compute more metrics/curves such as the Precision-Confidence curve, Recall-Confidence curve and Precision-Recall curve, however I cannot find where the precision and recall values for all the confidence scores are available.
Best Regards,
Joe

**Comment by mibaumgartner** [comment]
Dear @JoeNajm ,

the COCO metrics (AP, mAP) are computed here: https://github.com/MIC-DKFZ/nnDetection/blob/main/nndet/evaluator/detection/coco.py

Best,
Michael

**Comment by mibaumgartner** [comment]
Since there was no update for some time I’ll close this Issue for now.
Please feel free to reopen this Issue if the problem persists or open a new one.
