### ISSUE TITLE
nnUnet as detection

### ISSUE THREAD

**Issue by orouskhani** [MIC-DKFZ/nnDetection#99]
Hello Michael,

First, thanks for sharing nnDetection, that's interesting as well as nnUnet. 

I have already lunched and trained a nnUnet and saved the model for ADAM dataset. I read the instruction in nnDetection GitHub you talked about the application of nnUnet as detection.  However, I couldn't understand it very well. Could you please let me know and tell me the steps that how can I use nnUnet for detection task? I need the 3D coordination of lesion. 

Regards,
Maysam

**Comment by mibaumgartner** [comment]
Dear @orouskhani,

we only submitted nnDetection to the ADAM leaderboard, so there is no code available to compute the coordinates from the segmentations. The code to run the postprocessing from nnU-Net to extract bounding boxes which we used for our remaining experiments can be found here: https://github.com/MIC-DKFZ/nnDetection/blob/main/scripts/nnunet/nnunet_import.py . Is there something specific you are missing? 

Best,
Michael

**Comment by orouskhani** [comment]
Dear Michael,
Thank you for your response. 

You mean the nnunet_import.py can be given the model trained by nnUnet? You mean the nnunet_import.py can generate the bounding box?  

Regards,
Maysam

**Comment by orouskhani** [comment]
Dear Michael,

The output of nnDetection for ADAM dataset is to compute the aneurysm's coordination?  I mean, does the nnDetection print x,y,z (coordination of aneurysm) as output?

Regards,
Maysam

**Comment by mibaumgartner** [comment]
Dear @orouskhani ,

there is an additional script in the adam project folder which computes the coordinates from the predictions.

Best,
Michael

**Comment by orouskhani** [comment]
Dear Michael,
Thank you for your response. 

About the script you mentioned, is it the "convert.py" file in ADAM folder? 

Regards,
Maysam

**Comment by mibaumgartner** [comment]
Yes

**Comment by orouskhani** [comment]
Thanks for your reply. 

According to your previous responses, I can extract the bounding box from nnunet's output via nnunet_import.py. Then, the extracted bounding box can be given to convert.py to generate the 3d coordination of aneurysm. Is it correct?

Regards,
Maysam
